.travis.yml
echidna-manifest.txt
webdriver-spec.html

Only 3 things left (find 3 instances of `TO-DO` in my changes):
1. Enter the URL to the group's decision to publish.
2. Encrypt the token with Travis and paste the resulting string in `.travis.yml` ([instructions](https://github.com/w3c/echidna/wiki/Setting-up-Echidna-as-a-GitHub-hook)).
3. (Only if the spec is made up of more files than the index HTML) list all those files in `echidna-manifest.txt`.

Set up automatic publication with Travis & Echidna

---

webdriver-spec.html

Set Window Size returns the size of the window, but does so by calling
Get Window Size, which steps duplicate many of those already run. This
patch addresses this by abstracting the window size concept.

Make abstraction for window size

---

webdriver-spec.html

These are implemented in most drivers, exists in Selenium’s JSON wire protocol, but appears to have been lost in the transition to the spec.

Define set- and get window position commands

---

webdriver-spec.html

The variable "proxy autoconfiguration url" is referenced but never
defined. Marionette is currently looking for "pacUrl", which seems like
a fine name.

Define the property name for the PAC URL.

---

webdriver-spec.html

For commands that spin the event loop, it was decided by resolution
in the working group that they must listen for user prompts and take
appropriate action at _any_ point during their execution; not just at
the start of the command.

Invoke user prompt handler implicitly when executing script

---

webdriver-spec.html

This patch resolves an action from the WG F2F in July 2016.
When attempting to serialise a WindowProxy exotic object which associated
browsing context has been discarded, we return an error instead.

Error on serialising window of discarded browsing context

---

webdriver-spec.html

Resolves an action from the WebDriver F2F WG meeting in July 2016.
Define what it means to provide an HTTP frontend for the protocol.

Make normative reference to HTTP

---

webdriver-spec.html

Provides descriptions in the table of timeout types, renames the command
from Set Timeout to Set Timeouts in order to match the plurality of the
HTTP endpoint, and makes the type checks more strict.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/329)

Make type checks in Set Timeouts clearer and rename it to plural

---

webdriver-spec.html

No noteworthy functional changes
The element retrieval chapter is currently a bit unorganised. This makes the chapter look more like the other chapters, with subsections for locator strategies. It also moves general algorithms to the start of the chapter.
Some typo fixes and stylistic fixes included.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/331)

Reorder and fix section headers

---

webdriver-spec.html

The current top-level browsing context is changed implicitly by doing this.
Fixes #338.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/339)

Set the current browsing context when switching windows.

---

webdriver-spec.html

mismatched terms, horizontal center relates to width (not height)
vertical center relates to height (not width)
Fixes #424
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/426)

horizontal ~ width, vertical ~ height

---

webdriver-spec.html

Unless I am missing something.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/344)

Keyup for "Alt" sets `alt` property to false

---

webdriver-spec.html

In case this is a typo https://github.com/w3c/webdriver/issues/429
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/430)

Fix typo status command method

---

webdriver-spec.html

These two patches corrects the start nodes for element retrieval so that they don’t use the `<html>` element directly but instead the current document’s document element, and return the appropriate errors if the `value` and `using` fields are missing from the request bodies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/434)

Correct start nodes for element retrieval and error on missing args

---

webdriver-spec.html

duration is optional for pointerMove but required for pause. If we let it be optional for pause then "compute tick duration" would default to duration 0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/436)

Make pause duration optional

---

webdriver-spec.html

Fulfils resolution from F2F in Lisbon: https://www.w3.org/2016/09/19-webdriver-minutes.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/437)

Rename acceptSslCerts to acceptInsecureCerts

---

webdriver-spec.html

The DOMRect sequence returned from `getClientRects()` can be of length
0, which happens when the element’s `display` style property has the
computed value of `none`, amongst other things.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/441)

Check length of DOMRect sequence on pointer interactability

---

webdriver-spec.html

The list of endpoints had a different ordering to the navigation of the
specification. This was confusing as the navigation matched the layout
and ordering of the page, making the list of endpoints the odd one out.
This update reorders the list to be in line with navigation and the
order of the page itself.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/462)

Reordered list of endpoints to match navigation

---

webdriver-spec.html

Pull request for  https://github.com/w3c/webdriver/issues/467
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/468)

Simplify text by removing 'structure' from 'JSON Object structure'

---

webdriver-spec.html

Most "JSON Object" occurrences are `JSON <a>Object</a>` whereas a few are `JSON Object`. It looks the format could be unified (to `JSON <a>Object</a>`) without altering the text meaning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/469)

Unify format of all 'JSON Object' occurrences to 'JSON <a>Object</a>'

---

webdriver-spec.html

This is the only place where `sessionId` is used in the endpoint URL, all other occurrences are `session id`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/470)

Unify session id variable placeholder in endpoint URL

---

webdriver-spec.html

FETCH defines 'HTTP status' that is code not 'HTTP status code'.
Fix respec warning:
Found linkless <a> element with text 'http status code' but no matching <dfn>.  respec-w3c-common:1:26900
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/473)

Replace 'HTTP status code' with 'HTTP status'

---

webdriver-spec.html

Fix respec warning.
Found linkless <a> element with text 'ticks' but no matching <dfn>.   respec-w3c-common:1:26900
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/475)

Add dfn for plural of tick

---

webdriver-spec.html

Found linkless <a> element with text 'no such window.' but no matching <dfn>.  respec-w3c-common:1:26900
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/476)

Fix typo in <a> to match its dfn

---

webdriver-spec.html

The dfn for the table was missing. Also, updated an occurrence of a related <a>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/479)

dfn for 'table of standard capabilities'

---

webdriver-spec.html

Found linkless <a> element with text 'capability' but no matching <dfn>.  respec-w3c-common:1:26900
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/480)

Add data-lt singluar value in capabilities dfn

---

webdriver-spec.html

Fix warning
Found linkless <a> element with text 'data' but no matching <dfn>.  respec-w3c-common:1:26900
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/485)

Convert an <a> to <var> and change wording to match success definition

---

webdriver-spec.html

The <a> 'properties' (that belong to <var>data</var>) is an undefined
concept. However, the 'Cookie concepts' of the 'table for cookie
conversion' are well defined and can be used instead, making the text
more consistent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/486)

Remove undefined properties <a> and reword accordingly

---

webdriver-spec.html

And that they should return an error if there are no items
in the list returned by the finding algorithm.
This also cleans up the finding algorithm to remove the "all"
parameter.
This closes issue #463.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/488)

Indicate the the "find element" commands only return 1 element

---

webdriver-spec.html

Found linkless <a> element with text 'active user prompt' but no matching <dfn>.  respec-w3c-common:1:26900
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/491)

Correct <a> active user prompt to match <dfn> 'user prompt'

---

webdriver-spec.html

Found linkless <a> element with text 'perform actions' but no matching <dfn>.  respec-w3c-common:1:26900
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/492)

Convert attribute id to data-lt for dnf 'perform actions'

---

webdriver-spec.html

Currently, no other command in 'table of endpoints' uses the -ing form of
the command verbs. Corrected to make the text more uniform.
Found linkless <a> element with text 'releasing actions' but no matching <dfn>.  respec-w3c-common:1:26900
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/493)

Rename section title and reference 'Releasing Actions' to 'Release Actions'

---

webdriver-spec.html

When sending responses back to the local end we need to set the header
name 'Content-Type' with value 'application/json'.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/496)

Set the header in the response sent back to local end. Fixes #349.

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/499)

Correct link to location strategy in "session implicit wait timeout"

---

webdriver-spec.html

Commands "Get Window Size" and "Set Window Size" at their last success step return
> Return success with the JSON serialisation of the current top-level browsing context’s window size.
Whereas "Maximize Window" and "Fullscreen Window" at their last success step return
> Return success with the a new JSON Object:
>
> width
>    Current top-level browsing context’s window dimension width.
> height
>    Current top-level browsing context’s window dimension height.
which is effectively the same as the first one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/503)

Unify the return values for window related commands

---

webdriver-spec.html

But only when executing the high level "do as I mean" commands.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/504)

Indicate that the session implicit wait also applies to interactability

---

webdriver-spec.html

Add an origin property which allows pointer moves to either be relative to the viewport,
relative to the current pointer location, or relative to the centre point of an element.
This replaces the old element property and permits moveTo sementics from the current Selenium
API to be implemented.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/495)

Allow specifying an origin for pointer moves.

---

webdriver-spec.html

No <dfn> for webdriver in Navigator
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/509)

Add definition for Navigator.webdriver attribute

---

webdriver-spec.html

The concept "input cancel actions" is undefined and from reading the
algorthm it looks this step should be emptying the well defined
"input cancel list".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/511)

Correct <a> 'input cancel actions'

---

webdriver-spec.html

Removing valid from before Session Timeouts Configuration since the
object keys are linked in that sentence. The configuration will either have
the keys, making it valid, or it won't meaning it is invalid.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/516)

Remove 'valid' before capability name. Fixes #461

---

webdriver-spec.html

This brings us to parity with the existing Selenium implementation
of the command and closes issue #445. Notable changes:
* We now focus and unfocus the element. This will cause the
`change` event to fire if the content changes.
* Fire an `input` event if the element content changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/515)

Flesh out Element Clear command

---

webdriver-spec.html

Newer versions of respec identify the content of <dfn> as if it was
in the data-lt attribute. Everything works fine without this minor
cleanup change, it merely makes the HTML a bit more simple.
Fixes https://github.com/w3c/webdriver/issues/477
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/526)

Do no duplicate content of <dfn> in its data-lt attribute

---

webdriver-spec.html

Null and undefined are discrete types so we only need to check for
one of them when discussing JSON Objects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/531)

Remove superfluous use of null in capabilities checks. Fixes #454

---

webdriver-spec.html

Fixes part of https://github.com/w3c/webdriver/issues/529
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/548)

Unify wording for CSS class `.switch`

---

webdriver-spec.html

This effectively excludes the default- and user encode sets which
contains unwanted characters to include in the concatenated URL that
makes up the extension command URL.
Fixes: https://github.com/w3c/webdriver/issues/566
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/567)

Limit extension commands to lower ASCII alphabet code points

---

webdriver-spec.html

This allows users to do something like:
```
element.sendKeys("Hello Worlt!");
element.sendKeys(Keys.LEFT);
element.sendKeys(Keys.BACKSPACE);
element.sendKeys("d!");
```
and have that be equivalent to:
```
element.sendKeys("Hello Worlt!" + Keys.LEFT + Keys.BACKSPACE + "d!");
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/575)

`Element Send Keys`: Only focus element if necessary

---

webdriver-spec.html

Most commands were checking the top-level browsing context
rather than the current browser context. Review each command
and ensure that the correct browser context is checked for
whether it's open.
Closes #397
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/574)

Ensure the correct browsing context is checked per-command.

---

webdriver-spec.html

The rest of the window section has been tidied up to return a window rect
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/584)

Have Window Rect returned for all window commands

---

webdriver-spec.html

I followed the lead of the `HTTP status` links, however `HTTP status` is defined as such in the dependencies. 
I wasn't sure whether to prepend "HTTP" to the dependency names `Request` & `Response`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/593)

Convert HTTP response and HTTP request text to links

---

webdriver-spec.html

We currently refer to the input state object, but I think it’s clearer to call it an input state table, or possibly map.
This also fixes the reference to JavaScript, which should be ECMAScript.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/600)

Input state object is a table for clarity

---

webdriver-spec.html

Do this by renaming variables to something more human
readable, and iterating over properties without using
an index.
Closes #455. Closes #456
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/573)

Tidy up `Processing Capabilites`

---

webdriver-spec.html

This simplifies the (as yet unwritten) `processing keys`
algorithm, allowing us to break on grapheme clusters as
discussed at the Lisbon F2F.
This also rectifies a historical accident caused when
Selenium WebDriver moved from Java 1.4 to 5 and started
using varargs in the `sendKeys` command.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/603)

Element Send Keys: Make the `text` parameter a string.

---

webdriver-spec.html

Fixes https://github.com/w3c/webdriver/issues/565
Attempt to describe (not define) 'browser chrome' and 'browser chrome elements' in chapter [2. Terminology](https://w3c.github.io/webdriver/webdriver-spec.html#terminology#h-terminology)
Once this is settled I'll link text to it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/604)

Add non-normative description of 'browser chrome'

---

webdriver-spec.html

This introduces the ability to unset modifiers using the
`null` key (`\eE000`).
We still leave "`processing keys`" as poorly defined as
before this change, since I think we may need a follow
up diff to handle graphemes and properly define what
"processing keys" actually is.
Closes #553. Addresses #346
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/578)

`Element Send Keys`: base on top of `Actions`

---

webdriver-spec.html

The pointer-interactability test will always fail if the element is
obscured, but the intercepted element test will only fail if there is
another overlaying element.
To give the intercepted click test a chance to run, we need to run it
before testing for pointer-interactability.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/613)

Check if element is obscured before testing pointer interactability

---

webdriver-spec.html

We do this by sending composition events. This diff also
resolves the lack of a "processing keys" algorithm and 
handles most common cases when typing a normal string.
There is at least one edge condition (sending a right shift
keyboard input) that will cause unexpected text to be
typed.
Closes #506 and substantially addresses #346.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/610)

`Element Send Keys`: handle i18n input.

---

webdriver-spec.html

It’s worth pointing out that ReSpec takes care of this and lower-cases them when viewing the HTML document in a browser. However, it’s worth having the same consistency before us when we edit the document.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/623)

Avoid capitalisation of definitions in Nodes chapter

---

webdriver-spec.html

This PR addresses some fundamental misconceptions about pointer-interactability. My changes from earlier today in https://github.com/w3c/webdriver/pull/613 were misleading because I also mis-remembered how it worked.
Pointer-interactability and whether an element is obscured by another is the same basic idea: pointer-interactability assumes the element is inside the viewport, looks at the paint order and checks if the topmost non-transparent at the element’s centrepoint is itself. The obscured element test that was added recently to return a distinctive error message _is exactly the same_ as this check.
This PR changes the behaviour of the _element not interactable_ error to mean that it is outside the viewport. If the element is not pointer-interactable (that is, it is not ‘obscured’), …

Fix element click

---

webdriver-spec.html

The variable named "all" is not defined in the call sites for "Find,"
and "Find" does not define such a parameter. Remove the references to
the variable named "all" from the call sites.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/679)

Remove undefined argument

---

webdriver-spec.html

I think we could do a bit more cleanup here while we're at it. It seems as though the words "reference" and "parameter" that follow most current usages of "getting a known element by UUID" should be removed. Is that right?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/667)

Specify argument to "getting a known element"

---

webdriver-spec.html

Fixes: https://github.com/w3c/webdriver/issues/617
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/676)

Provide definition of transparent element

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/674)

Use trying macro throughout

---

webdriver-spec.html

It's entirely possible that the element may have
gone stale between command calls.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/687)

Check for element staleness when getting a known element

---

webdriver-spec.html

It's safe to remove this from the spec, as it's not
used by anything.
Closes #500. Closes #501 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/684)

The `global key state` definition is not referred to

---

webdriver-spec.html

But it may not be. Implementations need only ensure that the
reference is unique within the current session in order for
the protocol to work.
This allows implementors more latitude in how to create the
reference. The original IEDriver used a serialisation of the
COM object's address, and that would meet the constraints
required here too.
Closes #681
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/682)

An element reference should be a UUID

---

webdriver-spec.html

Step 2 of the Get Alert Text command dictates that an error must be
returned in the absence of a dialog. Update the command's description to
accurately summarize this behavior.
This resolves gh-631.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/688)

Correct contradictory description

---

webdriver-spec.html

TBH I wasn't aware what an ECMAScript "internal method" method is. This patch makes more explicit that it's something well defined somewhere.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/695)

Add dependency for ECMAScript internal method and links to it

---

webdriver-spec.html

The `isPrimary` property of a pointer event is specified as:
* Is the input source a mouse?
* Is this the first non-mouse pointer for a specific subtype
In neither case should webdriver be setting these values.
https://www.w3.org/TR/pointerevents/#the-primary-pointer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/707)

Remove `primary` from the pointer input sources.

---

webdriver-spec.html

There was no check to ensure this. Also fixes a problem
where the link `JSON Serialization` exactly matched a
definition, and so linked to the wrong place.
Closes #693
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/694)

`Find` algorithm: ensure all elements are actually elements.

---

webdriver-spec.html

This clears up the current respec warnings in the spec,
but it's a little clumsy --- the `input state table` is not
really necessary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/709)

Define `input source state` and `input state table` and use them

---

webdriver-spec.html

An element's container element is always in the last resort the element
itself.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/717)

All elements have container elements

---

webdriver-spec.html

We want to check if we are able to get the the element to click into the viewport before checking if we can pointer-interact with it.
If the element is obscured by another element or otherwise cannot be brought into view, we would otherwise end up waiting for the timeout duration before returning an error to the user.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/718)

Try getting element in view before testing pointer-interactability

---

webdriver-spec.html

This allows subsequent commands to run cleanly and
matches the behaviour of existing imeplementations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/725)

`User Prompts`: unexpected prompts cause prompt to be dismissed

---

webdriver-spec.html

Instead of acting like one we now need it to be a HTTP server.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/729)

Specify that remote end must be a HTTP server. Fixes #661

---

webdriver-spec.html

Local end should remove `*` and `ANY` entries from capability
objects. They may, optionally, instead set the value to null.
Closes #711
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/728)

`New Session`: ignore wild cards

---

webdriver-spec.html

I've used SHOULD instead of MUST to give implementations some
latitude in OS naming.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/731)

`New Session`: list commonly used platform names

---

webdriver-spec.html

We need to check if only the fragment has changed and if it's only
a fragment change then we don't need to do as many of the post
checks for this command as it won't fire any events
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/736)

Do not wait for page load if only the fragment changes. Fixes #706

---

webdriver-spec.html

Tightens the contraints on proxy objects and ensures
that they are valid in `New Session`.
Closes #635
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/732)

`New Session`: check that proxies are valid

---

webdriver-spec.html

Removing this sinces its going to be a continual moving target
and is not used by any of the major cloud providers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/743)

Delete platformVersion capability since its not used. Fixes #741

---

webdriver-spec.html

I believe this modification is in-line with the authors' underlying intent.
Please note that it also enables a new usage whose validity is a little more
ambiguous: the explicit specification of `null` parameter values, e.g.
```json
{
"x": 23,
"y": null,
"width": 800,
"height": 600
}
```
Commit message:
> Previously, the language that allowed for unspecified parameters was
> unreachable because a prior algorithm step returned an error in their
> absence.
>
> Defer enforcement of parameter type until after they have been extracted
> from the "parameters" argument. This ensures that unspecified values are
> accepted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/745)

Get Window Rect: Make all parameters optional

---

webdriver-spec.html

* mixing definitions and non-normative language
* The "session is created by a New session request" is repeated twice
* The "remote end that is not an intermediary node has at most one
active session at a given time." clarification is mentioned twice,
but never alongside the definition of "active sessions".
Suggestion for https://github.com/w3c/webdriver/issues/721 I apologize if the suggestion reflects personal taste, rather than an actual text flow improvement.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/739)

Improve the text flow in the Session section introduction

---

webdriver-spec.html

This removes the check for opacity in interactability checks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/747)

Allow hit testing to handle first interactable element. Fixes #746

---

webdriver-spec.html

This places the definition of the generic "input state"
term at the top of the section, then proceeds to list
the specialisations before explaining what the "input
state table" and "input cancel list" are. This feels
like a more sensible ordering for this section of the
spec.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/759)

`Actions`: Shuffle content around

---

webdriver-spec.html

This allows us to properly validate the parameters given
to an action sequence.
This diff also causes webdriver implementations to create
new input sources as necessary. #progress
Address issue #691
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/761)

`Actions`: Track the known input sources

---

webdriver-spec.html

The 'Privacy' and 'Security' sections exist but the respec lib
complains because they are not named 'Privacy Considerations' or
'Security Considerations':
This specification doesn't appear to have any 'Privacy'
or 'Security' considerations sections. Please consider
adding one, see https://w3ctag.github.io/security-questionnaire/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/767)

Append Considerations to Privacy and Security chapter names

---

webdriver-spec.html

This simplifies some of the later logic and means
that all the fields of the returned result have
defined values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/769)

`Processing Capabilities`: don't include null values when merging capabilities

---

webdriver-spec.html

This allows us to be able to get the value from other elements,
like SVG Elements, instead of just working with HTMLElements
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/768)

Return point for all elements not just HTML Element. Fixes #392

---

webdriver-spec.html

I initially attempted to define this capability in terms of, "querying/modifying the top-level browsing context's window rect." That language is not quite accurate, though, since it doesn't necessarily describe "Minimize Window." So that's why I'm suggesting referencing "the commands in Resizing and Positioning Windows" instead. It's less precise, and I couldn't find any precedent for it, so I'm wondering if there's a better way.
I believe this exposes the following behavior, given the listed "capabilities" objects:
- `{ "setWindowRect": true }`: user agent MUST support *every* command in
"Resizing and Positioning Windows"
- `{ "setWindowRect": false }`: user agent MUST NOT support *one or more*
commands in "Resizing and Positioning Windows"
- `{}`: user agent MAY support all commands in …

Introduce capability: `setWindowRect`

---

webdriver-spec.html

Duplicate definition of 'window dimensioning/positioning'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/778)

Fix respec warning about duplicate definition

---

webdriver-spec.html

By the time we're processing pointer actions we've
already been through the steps of processing an action
sequence. Within _those_ steps we've already checked
that the input state within the `input state table`
correctly matches expected type for the pointer action.
Address issue #691
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/781)

`Actions`: Remove duplicated input state check

---

webdriver-spec.html

Closes #636 amongst others.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/755)

Capabilities strategies

---

webdriver-spec.html

Almost every other key in the spec uses camel case instead of spaces. This makes it easy in Ruby to implement with immutable symbols. Having a space in a key requires it to be a string. I can obviously make a special translation method if this needs to have a space, but it would be great if that could be avoided.
The only other keys I see that have spaces are the locator strategies, but those are easily handled in the implementation abstraction rather than being part of a user-facing object (like `Capabilities`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/787)

use key of 'pageLoad' instead of 'page load' in timeout capability

---

webdriver-spec.html

In some cases, this means that we've also had to futz with
the spec text, but the logical meaning should be identical.
The W3C link validtor does not correctly check links into
PDF documents, however loading these in Chrome show that
they are valid.
I've removed the test about showModalDialog since this
method has been removed from modern browsers and is no
longer supported.
This does not fix the broken link in the execute script
section
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/791)

Fix up links identified as being dead or incorrect

---

webdriver-spec.html

There's no reason to discriminate. We rely on the fact that
the focusing and unfocusing steps are run in order to ensure
that the correct "onchange" event is fired. Existing
implementations based on Selenium's "atoms" don't bother
firing an `input` event, and so neither do we.
As specced, this is a slow-motion way of calling a form's
`reset` method with additional focusing steps. It fulfills
the need of users to reset form fields to their default
values.
Closes #561
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/798)

`Element Clear`: Apply to all resettable elements

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/805)

Allow window position to be set with negative integers

---

webdriver-spec.html

Avoids a potential issue with low wait timeouts and
smooth scrolling.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/792)

Scroll into view: do so instantly

---

webdriver-spec.html

It's completely legit to click on an element that is not
enabled. Pointless, but still acceptable. The existing
Selenium implementations (based on the atoms) do not bother
with checking this state, so it seems unnecessary for
implementations of this spec to do so.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/793)

`Element Click`: no need to check enabled state

---

webdriver-spec.html

A previous change (#787) changed `page load` to `pageLoad`
but we missed the similar change in the `timeouts configuration
object`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/796)

`Timeouts`: Standardise `pageLoad` rather than `page load`

---

webdriver-spec.html

In the `send a response` algorithm, when the data to be returned as the
response for a command is `null`, it should be wrapped in a JSON object
with a `value` property set to `null` rather than sending no body. Fixes
issue #807.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/808)

Null data on response should be wrapped in JSON object

---

webdriver-spec.html

This simplifies some of the language in the rest of
the spec by reducing boilerplate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/809)

Make scroll into a view a no-op if the element is in view

---

webdriver-spec.html

When deserializing, be kind to folks who are using enums
in the local end and have sent the names of the proxyType
in upper case.
Closes #803
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/811)

Look up proxyType case insensitively

---

webdriver-spec.html

We should move the element into view before trying
to check whether it's keyboard interactive.
There's no point getting the text length if we're
just going to set the selected files for a `file`
INPUT element.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/814)

`Element Send Keys`: Reorder steps

---

webdriver-spec.html

Rather than spreading the ideas in multiple places, gather
all information about timeouts and their configurations in
one place.
Closes #806
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/813)

Locate all timeout configuration in one place.

---

webdriver-spec.html

Let's go shopping. Or, alternatively, try and find the first
ancestor datalist element. If that doesn't exist, then use
the first ancestor select element.
Closes #735
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/817)

Element containers for OPTION elements are hard.

---

webdriver-spec.html

What's in the spec for intermediary nodes isn't sufficient to
write one that correctly handles the webdriver protocol. We're
going to need some better definitions, and these will be
simpler to write if we've already defined what "upstream" and
"downstream" mean.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/820)

Intermediary Nodes: it's useful to define upstream and downstream

---

webdriver-spec.html

It should be possible to use `Element Send Keys` to
set the value of INPUT elements that are rendered
as something other than a text control. We do this
by allowing users to send form-serialized values to
the element and setting the value directly.
Closes #535
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/799)

`Send Keys`: Allow HTML5 values to be sent

---

webdriver-spec.html

The other example contained some misleading suggestions,
such as including authentication tokens for intermediary
nodes in the body of the capabilities.
Closes #819
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/823)

Make extension capability example easier to understand

---

webdriver-spec.html

Fixes https://github.com/w3c/webdriver/issues/826
The introduction of the New Session command lists a number of reasons
for failing to create a new session, but these are already defined in
the algorithm. This causes the overhead of keeping the introduction
in sync with any algorithm changes.
Currently, the introduction was missing:
* a definition for: provisioning of a remote end
* failing due to a user prompt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/827)

Simplify the introduction of New Session command

---

graphics/note1actions.svg
graphics/note2actions.svg
graphics/note3actions.svg

Fixes https://github.com/w3c/webdriver/issues/842
The new tick labels have not been centered with the above rectangles.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/843)

Action examples diagrams should group actions by ticks

---

webdriver-spec.html

An intermediary node needs to route commands to an upstream
node rather than acting upon them directly. A later PR will
include the mechanism for doing this, but for now track the
session that's been opened upstream and ensure that it will
be closed properly at the end of the session.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/824)

Introduce the concept of an associated session

---

webdriver-spec.html

If there is a prompt before we do newSession it will be hard to do
anything until we have a session.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/854)

Remove prompt check from newSession as it happens to early. Fixes #829

---

graphics/note2actions.svg

In the rest of the diagram examples the actions are horizontally
grouped by source, not action. Also, it's referenced like that in the
diagram explanation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/846)

Action example diagram should use source instead of action

---

webdriver-spec.html

The atom here is aware of the ShadowDOM and so should produce
better results if that's used. It's functionally equivalent
to the version used in Selenium 3.1
Closes #413
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/714)

`Get Element Text`: use the ECMAScript atom

---

webdriver-spec.html

Some existing clients (Java, notably) send the value in all-caps.
Addresses #835.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/870)

Make proxyType value comparison case-insensitive.

---

webdriver-spec.html

In the phrase, "the first matching user prompt handler," the word
"first" may be interpreted in one of two ways:
1. There are multiple user prompt handlers from which the match may draw
2. There are multiple matching options in the list that follows
The first interpretation is incorrect because a session has exactly one
value for the user prompt handler. The second interpretation is also
incorrect because the available options are mutually exclusive (so
their sequence does not matter).
Re-phrase the language to avoid this ambiguity, borrowing verbiage from
the "close the session" algorithm as currently defined in the
specification.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Re-phrase language for branching logic

---

webdriver-spec.html

A fix for https://github.com/w3c/webdriver/issues/865 (provided this is indeed missing)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/866)

Add current top-level browsing context check to Release Actions

---

webdriver-spec.html

Thanks to @foolip.
Fixes: https://github.com/w3c/webdriver/issues/881
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/882)

Fix string constant language

---

webdriver-spec.html

I didn't see a variable `matched capability` anywhere and it seemed more reasonable to suppose we're setting a name and value on the capabilit_ies_ object, so I figured this was a typo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/890)

fix typo in capability matching section

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/889)

Make Send Alert Text take a string text field

---

webdriver-spec.html

The definition of "maximum active sessions" states:
> [...] must be exactly one for a remote end that is an endpoint node.
This restriction is further supported by the definition of "active
sessions," which states:
> A remote end that is not an intermediary node has at most one active
> session at a given time.
Therefore, the "readiness state" for endpoint nodes can be described in
terms of a precise number ("one") of active sessions. The additional
state concerning the current user prompt is subsumed by this condition.
Simplify the definition of "readiness state" to reflect the limitations
of endpoint nodes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/883)

Simplify definition of "readiness state"

---

webdriver-spec.html

As the options of a `<select multiple>` are painted and represented as DOM
elements, the center point would end up targetting one of the `<option>`
elements.  We can take this into account by using `select.contains(option)`.
If the first pointer-interactable paint tree element is itself, this is
also passes the check, since the `DOMElement.contains(otherEl)` performs
an _inclusive_ descendant check.  This means `element.contains(element)`
is true.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/894)

Take <select multiple> into account in obscured element test

---

webdriver-spec.html

When an element has pointer events disabled, e.g.
`<input type=button style="pointer-events: none">`,
it does not appear in the paint tree acquired from
`document.elementsFromPoint`.
To circumvent this issue and make element in view checks possible for
elements which don’t have pointer events enabled, we need to run the
check as if pointer events were enabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/896)

Test in view with pointer events enabled

---

webdriver-spec.html

WebDriver commands are currently written to reference "URL variables" by
name. For example (from the "Element Send Keys" command):
>     <li><p>Let <var>element</var> be the result
>      of <a>trying</a> to <a>get a known element</a>
>      with argument <var>element id</var>.
This is in conflict with the current command invocation, where
they are specified as a collection of name-value pairs.
In addition, some commands reference an argument named "parameters" that
is expected to contain the parsed request body. For example (again from
the "Element Send Keys" command);
>     <li><p>Let <var>text</var> be the result
>      of <a>getting a property</a> called "<code>text</code>"
>      from the <var>parameters</var> argument.
However, this argument is not currently provided when the …

Correct specification of command arguments

---

webdriver-spec.html

Both of the RFCs linked to limit the SOCKS
version to a single byte.
Closes #899
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/904)

Limit valid range for socksVersion

---

webdriver-spec.html

We mis-used this for `proxyType`, and failed to
reference it when matching capabilities.
Closes #835
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/908)

Correct use of `lowercase`

---

webdriver-spec.html

This is what `JSON.stringify` does, and so brings
our algorithm more closely into line with what a
user might expect to happen, and prevents some of
the potential failures from calling `Execute Script`
(eg. `return window.performance`)
Closes #849
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/906)

When cloning a JS Object, look for `toJSON`

---

webdriver-spec.html

In the other places where the spec talks about
the `page loading strategy` we already state
that it defaults to `normal`, and we will have
removed `null` values while processing
capabilities.
If a user attempts to set the `page loading
strategy` to `null` via `Set Timeouts`, then
that is clearly an error.
Closes #834
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/907)

There is never a `null` `page loading strategy`

---

webdriver-spec.html

As pointed out in #839, a URL "consisting of just
the domain and the port" is unclear. We already
link to the relevant parts in the URL spec to
define both `domain` and `port`, so just rely on
those instead.
Closes #839
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/909)

Clarify that proxy hosts are domains and ports.

---

webdriver-spec.html

This makes the navigator.webdriver property unconfigurable.
Fixes: https://github.com/w3c/webdriver/issues/914
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/918)

Mark navigator.webdriver as unforgeable

---

webdriver-spec.html

For implementation compatibility we should not try to close the session
if the session does not exist.  This can be interpreted in different
ways because of the use of the "try" algorithm.
Instead we make the Delete Session algorithm explicitly call out that
the session must be active in order to attempt closing it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/926)

delete session: close session only if it is still active

---

webdriver-spec.html

Remove mentioning of DoS attacks and accent that this is a _standard_ way of advertising by UA that it is controlled by WebDriver.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/920)

Rephrase description of navigator.webdriver

---

webdriver-spec.html

It does not make sense to talk about the target of keyboard interaction
when defining which elements are keyboard interactable.  This belongs in
the key dispatch section in the chapter on actions.
I believe it is also inferred what the default target of the interaction
should be through the pointer events standard.
Fixes: https://github.com/w3c/webdriver/issues/886
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/910)

Omit ownerDocument when defining keyboard-interactable element

---

webdriver-spec.html

This, by necessity, needs to be done in an
implementation-spefific way. I've avoided using
language that ties the spec to only automating
browsers, since there are already implementations
for mobile devices, and even automating Windows
and OS X.
Closes #924
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/929)

Set the top-level browser context to use for a session.

---

webdriver-spec.html

If the current browsing context is no longer open then
we can safely assume that its navigation has completed.
This might be the case where a `click` has caused some
long-running JS to complete and then close the current
div or window.
I think that this fully addresses the problems in #871.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/932)

Only wait for navigation to complete if it can.

---

webdriver-spec.html

In rare circumstances, the current browsing context's document element
may be null. This will be the case, for example, after execution of the
following JavaScript:
document.documentElement.remove();
Without accounting for this condition in the "Find Element" and "Find
Elements" commands, the element location strategies may be invoked with
the null value as the "start node." From WebDriver's "find" algorithm:
> 5. Let elements returned be the result of the relevant element
>    location strategy call with arguments start node, and selector.
This invocation would produce a TypeError, which would be reported as an
"invalid selector" error:
> 6. If a DOMException, SyntaxError, XPathException, or other error
>    occurs during the execution of the element location strategy,
>    return error …

Find Element(s): check for null documentElement

---

webdriver-spec.html

The `Delete Session` may be called without an active
session, in which case it's a no-op. The processing
algorithm would never let this be the case, so needed
to be updated too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/928)

Allow `Delete Session` to be called without an active session.

---

webdriver-spec.html

Because browsing contexts may modify the built-in
`Element.prototype.getElementsByTagName` property value (or define a
distinct value for a given Element instance), invoking the function as
defined by a given node may produce unpredictable results.
Modify the text to reference the built-in function generically, avoiding
this ambiguity and increasing parity with similar algorithm steps in
related locator strategies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/938)

find: Avoid reliance on property value

---

webdriver-spec.html

Specify all parameters as required by the `evaluate` function, and
normalize the return type according to the structure expected by the
"find" algorithm (i.e. a NodeList).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/939)

find: Correct implementation of "xpath" strategy

---

webdriver-spec.html

- Update the "match a request" algorithm to refer to the term URI
template definition (instead of a local variable bearing that name).
- Update each Command's "overview" table to refer to "URI Template"
(instead of "Path Template") in order to align with the
specification's "table of endpoints".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/953)

Normalize references to URL templates

---

webdriver-spec.html

The "New Session" command does not specify a session identifier, nor
does it depend on the "current session" variable. This is also true of
the "Status" command, and any number of extension commands may likewise
operate outside the context of any particular session.
Skip the substeps related to the current session for any command that
does not specify a "session id" variable. Introduce a non-normative note
documenting the intention of this condition since it is partially
intended to satisfy externally-defined criteria.
Furthermore, processing such commands should not involve extracting the
"session id" value from the variable named "url variables". Re-locate
that step to the branch that concerns only those commands where it is
relevant.
---
This change is [<img …

Account for any session-independent commands

---

webdriver-spec.html

We use lower casing in definitions, so we should use it consistently.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/960)

fix capitalization of JSON serialization

---

webdriver-spec.html

Because the "send an error" algorithm provides error data as an
argument to the "send a response" algorithm, the JSON body is expected
to contain a "value" attribute whose value is an object describing the
error. Update the non-normative description and example to reflect this.
The remote end processing model explicitly allows invalid session IDs to
be specified to the Delete command. Update the example to use a command
which would respond to an invalid session ID with the "invalid session
id" error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/959)

Correct "error" example

---

webdriver-spec.html

The conditions described by this step (i.e. an unspecified property or a
non-string property value) are a subset of the cases described by a
subsequent step (i.e. value that is neither an absolute URL, an absolute
URL with fragment, nor a local scheme). Because the observable behavior
is identical in both cases, the former step is not necessary.
Remove the step in order to reduce algorithm complexity.
---
I'll admit that there's something to be said for explicitness, although if that
is the goal, there may be better alternatives to make this seem more
intentional (e.g. a non-normative Note explaining that missing or non-string
property values are also rejected by the URL validation step.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Go: Remove unnecessary step

---

webdriver-spec.html

Because "get a known element" is a algorithm with a formal definition,
it should be referenced with an anchor tag. Correct one such reference
which erroneously used the `<var>` tag.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/942)

Pointer actions: correct algorithm reference

---

webdriver-spec.html

During normal operation, the "find" algorithm returns a JSON List value.
Under exceptional circumstances, however, it returns a WebDriver error
value. Callers that manipulate the value must account for both cases
separately.
Update two such callers (the "Find Element" and "Find Element from
Element" commands) to account for the exceptional case by relying on the
specification's "try" construct.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/944)

Find Element: Account for WebDriver err from find

---

webdriver-spec.html

Each locator strategy may produce an error during execution. This
behavior is distinct from returning a WebDriver error value and is
handled by the text "if [an error] occurs," in the "find" algorithm.
However, in addition to producing an error in this way, the "xpath"
locator strategy may return a WebDriver error.
Update the "find" algorithm to handle this case by relying on the
specification's "try" construct.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/941)

find: Account for WebDriver error from locator

---

webdriver-spec.html

The same object value may occur as the value of multiple properties
within a single data structure without producing cycles. The array
created in the following JavaScript program is one such example:
var obj = {};
[obj, obj];
Update the "internal JSON clone" algorithm to support such structures.
---
This patch is intended to resolve gh-931. As suggested there, I've taken a cue from [the JSON.stringify method defined in ECMA262](https://tc39.github.io/ecma262/#sec-json.stringify).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/943)

JSON clone: correct cycle detection

---

webdriver-spec.html

Interpret the URI parts specified by extension commands as templates,
thereby allowing for extension commands such as `/session/{session
id}/permissions/grant`. Include a non-normative note to call attention
to the implicit "session retrieval" behavior of the command processing
model.
---
This is an initial pass at resolving gh-961. There, I pointed out that the command processing model's "session retrieval" behavior may not be apparent to those reading this section. I believe this justifies a non-normative note to call attention to that behavior.
@shs96c RFC6570 defines [distinct "levels" for templates](https://tools.ietf.org/html/rfc6570#section-1.2). So far, it seems as though WebDriver and its extensions may only need the capabilities of so-called "Level 1 templates". Do you see any …

Define extension command URI parts as templates

---

webdriver-spec.html

The name variable can not be invalid as this would lead to a different
URL leading to Unknown Command error being thrown.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/966)

Remove unnecessary name validation step from Get Element Attribute

---

webdriver-spec.html

- expose `navigator.webdriver` if UA is controlled by WebDriver (fixes #947)
- drop [Unforgeable] (fixes #922)
- extend Navigator through mixin (fixes #923)
/cc @annevk, @foolip
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/948)

Changes around navigator.webdriver

---

webdriver-spec.html

Also Americanises the spelling of "serialised cookie".
Closes #957
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/969)

Don't set expiry on a session cookie

---

webdriver-spec.html

We want to set the session's current browsing context from the associated
browsing context of the found WindowProxy object.  Each WindowProxy
has an associated browsing context, and the "new window" variable we
currently use is not defined.
Fixes: https://github.com/w3c/webdriver/issues/973
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/975)

switch to frame: set browsing context from child window variable

---

README.md

Remove obsolete W3C bug tracker link.
The component no longer exists, and the link leads to the message:
Sorry, the product Browser Test/Tools WG has to have at least one
active component in order for you to enter a bug into it.
As issues should just be filed using the GitHub issue tracker
here, I chose to simply remove the old link.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/978)

Remove obsolete W3C bug tracker link.

---

webdriver-spec.html

MouseEvents contain references to the modifier keys,
and these should be calculated as required.
https://www.w3.org/TR/DOM-Level-3-Events/#interface-mouseevent
Closes #595.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/968)

Make pointer events include the aggregated key state

---

webdriver-spec.html

When an OS window is minimised/maximized/fullscreened, there is currently
no homogenous way of telling what state it is in.
This introduces a "state" field on the window rect which returns the
window's state that is applicable for the current UA and the current
system.
The motivation behind this change is to make it easier to test the
specification, but I imagine it is also useful to users who want to
query the window's current state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/985)

window rect: introduce window state concept

---

webdriver-spec.html

A window's maximized state is often not the same as increasing its
dimensions to the maximum allowed screen size.  We need to be explicit
that the OS window should be moved into the maximized state.
Furthermore, a certain variety of window managers does not support the
concept of window maximation at all.  In this case, it is permissable for
WebDriver to increase the window's boundaries to the maximum screen size.
In the latter case, it is impossible to tell when if the window
has reached the full dimensions of the available screen, because
the window may have decorated borders.  This causes there to be an
unknown disjunction between window.screen.availHeight/availWidth and
window.outerWidth/outerHeight.  In this case we need to permit the
WebDriver implementation to return after a …

maximize window: transition to maximized state and make wm provisions

---

webdriver-spec.html

To align the specification with existing implementations, `<option>`
elements which are in the selectedness state and whose container element
is `<select multiple>` should be deselected when they are clicked.
`<option>`s that are child elements of a regular `<select>` dropdown should
not be deselected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/991)

element click: deselect selected <option> in <select multiple>

---

webdriver-spec.html

It is the intention that calling the Minimize Window command a second
time will restore it to its original dimensions on the visible screen.
It looks like an oversight that the specification does not cater for this.
This patch also makes it crystal clear that minimizing or restoring
the window must happen synchronously and not return before the
visibilitychange DOM event has fired.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/987)

minimize window: make it possible to restore the window

---

webdriver-spec.html

Setting a user prompt handler accepts or dismisses a prompt with no
notification to the user that the prompt was handled. In the primary use
case of testing, this hides important information from the user, that a
prompt the test did not expect was encountered, and handled. If the user
wishes to have their test ignore this case, they should make a fully
informed and conscious decision to do so. This change adds options to the
user prompt handler to allow for the case to inform the user of the
handled propmt via an error. To maintain compatibility with previous spec
language, the added values are the ones that describe the new behavior.
Closes issue #912.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Add states to prompt handling to allow notification of handled prompts

---

webdriver-spec.html

The spec carefully carved out space for commands to not
require a session (which is good), and then only singled
out `Delete Session` (which is an oversight). Fix this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/976)

Processing Model: allow any sessionless command to proceed

---

webdriver-spec.html

This includes an update to the atoms that better
handles the ShadowDOM using the final APIs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1002)

Bump version of the Selenium atoms to use

---

webdriver-spec.html

Minimize Window is the only window manipulation command
that toggles the state of the window when called.
This helps to address #1007. The way to restore a
window from minimized, fullscreen, or maximized state
is to call `Set Window Rect`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1013)

Make Minimize Window idempotent

---

webdriver-spec.html

Just in case `outerHTML` is set to do something odd.
Fixes #1003
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1010)

Clarify the language in Get Page Source.

---

webdriver-spec.html

To be something that is actually an invalid element state.
Closes #989
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1014)

Correct `invalid element state` example

---

webdriver-spec.html

If someone tries to set the socks proxy they
also need to declare the socks version.
Closes #1008
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1012)

Socks Proxy requires Socks Version

---

webdriver-spec.html

This is clearly meant to be allowed, since the spec
has language to say that implementation-specific
timeouts are supported.
https://w3c.github.io/webdriver/webdriver-spec.html#dfn-session-timeouts-configuration
Closes #1016
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1017)

Allow getting and setting of implementation-specific timeouts

---

webdriver-spec.html

Unless we have at least one entry in the list of
`firstMatch` the `New Session` algorithm will
never attempt to perform merging with `alwaysMatch`
meaning that a structure like this:
```
{
"capabilities": {
"alwaysMatch": {},
"firstMatch": [],
}
}
```
won't successfully start a session.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1019)

New Session: firstMatch must have entries

---

webdriver-spec.html

Resolves issue 1 on the spec. The language is wooly, but then
all the language around how to handle the network connection
is wooly. The key benefit of unknown error is that it sets the
http status code to 500, which is what I'd expect to happen.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1024)

Return an unknown error if an http request makes no sense

---

webdriver-spec.html

Since many of the implementations of webdriver are OSS
it should be trivial to remove the interface change and
make automation undetectable unless you use some other
means to spot it.
The comment itself is frivolous and unhelpful to spec
developers, but it's quite fun to have it be there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1025)

Acknowledge the evil-bitness of interface change

---

webdriver-spec.html

Otherwise cloud-providers are not going to get their
authentication tokens.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1032)

Top-level options MUST be forwarded

---

webdriver-spec.html

For an implementation that deseralizes the parameters in a frontend
before contacting the browser it's difficult to check for unexpected
alerts or perform other actions that require the browser before
completing deserialization. So ensure that deserialization is always
fully complete before taking other actions. In practice the only
observable change here is the error observed if there is both an
invalid request and e.g. an unexpected alert open.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1036)

Ensure deserialization of parameters happens before other checks.

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1040)

Rename Go to Navigate

---

webdriver-spec.html

The current algorithm for finding out if an element is stale, that is
conencted to the current document, does not take into account the fact
that an element may have a shadowRoot element as its document element.
Additionally, this shadow root may sit inside a possibly infinite number
of othe shadow roots.
Fixes: https://github.com/w3c/webdriver/issues/1055
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1056)

is stale: take shadow root into account

---

webdriver-spec.html

Any command which invokes the user prompt handler may optionally include
a "text" field with the user prompt's message.  This patch formalises
"error data" and "user prompt message".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1063)

error handling: formalise optional error data

---

webdriver-spec.html

The `match a request` algorithm does not mention extension
commands, making them unroutable by a struct interpretation
of the spec. Acknowledge that they are appended to the
table of endpoints, and everything should Just Work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1067)

Allow extension commands to be routed

---

webdriver-spec.html

Because it's about retrieving an element.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1071)

Move Get Active Element to Element Retrieval

---

webdriver-spec.html

They'd been edited so much they didn't make sense as English
sentences.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1064)

Write the definitions used by Algorithms in English

---

webdriver-spec.html

The text modified is already in a block where we've checked
for the presence of the session id in the url variables. If
there's no session, we should exit immediately. Moved that
step up to bring it closer to the loading of the session and
the declaration of session id from the url variables.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1065)

Simplify language when checking if session is present

---

webdriver-spec.html

The definition of `parse as JSON` does not return an
error or success with data. Instead, it's defined as
being equivalent to calling `JSON.parse`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1066)

JSON parsing is not a `tryable` function

---

webdriver-spec.html

So if we ever add more, we don't need to find all the
places the valid values are listed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1069)

Refer to the page load types indirectly

---

webdriver-spec.html

Turns out the list of valid entries is far broader:
https://developer.mozilla.org/en-US/docs/No_Proxy_For_configuration
Closes #1068
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1070)

Loosen `noProxy` values.

---

webdriver-spec.html

The number of steps in the algorithm to calculate an element's absolute
position is excessive.  This is more terse and easier to understand when
reading prose.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1073)

calculate the absolute position: make algorithm more concise

---

webdriver-spec.html

The check for whether an element is connected does not take into account
that the document may have changed.  This is a special case for WebDriver,
where element references are preserved across documents.
To work around this issue we compare the element's node document
(element.ownerDocument) to the current browsing context's active document
(element.ownerDocument.defaultView.document).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1072)

is stale: take document into account

---

webdriver-spec.html

To avoid shadowing attributes set in the DOM, we should rely on the
algorithmic definitions of ownerDocument, which is node document, from
the DOM specificaiton.
This patch also removes the third step as the otherwise-clause needs to
be part of the same step as the if-condition.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1074)

not in the same tree: use node document over ownerDocument attribute

---

webdriver-spec.html

As we agreed last week, deserialisation steps must come before the
remaining endpoint node steps.
This patch also fixes a bug where "scroll" came out of nowhere.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1076)

take element screenshot: deserialise input before other steps

---

webdriver-spec.html

In specifications we want to compare ourselves with, null and undefined
are not given a special <code> tag.  Null and undefined types are no
different to strings or arrays.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1075)

stop styling null and undefined types

---

webdriver-spec.html

In the existing spec, getting an element will return any element,
possibly in any browsing context, regardless of whether it's connected
to the document tree. This is clearly wrong:
* Only the list of known elements for the current browsing context
should be used. That is intended by the current spec, but the text
is unclear.
* For operations that depend on layout, interation, scrolling, etc. we
should ignore elements that are not connected to the document tree
(e.g. the result of createElement). For operations that only depend
on DOM or scripting, the possibility of working with such
disconnected elements makes sense. So we need to differentiate these
cases.
This commit fixes both the above issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

Differentiate connected and unconnected elements for getting a web element.

---

webdriver-spec.html

But without stealing OS level focus.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1083)

Make it clear that browser contexts should be focused

---

webdriver-spec.html

The screenX/screenY/outeWidth/outerHeight attributes on the Window
interface should according to CSSOM-VIEW be longs.  WebIDL defines longs
as platform-independent signed 32-bit integers, which means the bitness
of the platform does not come into effect.
We don't want the input to WindowProxy.moveTo or resizeTo to be larger
than the supported numbers it can take.  This patch reduces the allowed
sizes to i32s.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1084)

set window rect: restrict to signed 32-bit integer input

---

webdriver-spec.html

window.print creates an OS level dialogue that no drivers should be
allowed to interact with.
Fixes: https://github.com/w3c/webdriver/issues/1090
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1091)

user prompts: drop mention of window.print

---

webdriver-spec.html

Remove unnecessary 'a' in  'consisting of a three ticks'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1094)

Fix minor typo

---

webdriver-spec.html

This has not been implemented in any webdriver implementation
and so is being lifted to Level 2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1144)

Remove the ability to return a window or frame from execute script

---

webdriver-spec.html

This is not implemented in two separate implementations of
webdriver. Punting to level 2, but specifying unconfigurable
default behaviour for handling user prompts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1145)

Remove the configurability of the user prompt behaviour

---

webdriver-spec.html

It does not make any sense to say that the connection is being
terminated as the wire protocol is implemented over HTTP.
It also mentions that the top-level browsing contexts associated
with the current session should be closed, which is not the case with
all drivers.
The whole paragraph, overall, is informative and could easily be
mistaken for a normative paragraph.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1107)

delete session: remove inaccurate non-normative paragraph

---

webdriver-spec.html

The two first paragraphs introducing the Status command could be
mistaken as normative.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1108)

status: make introduction non-normative

---

webdriver-spec.html

This paragraph does not really say anything not already obvious and
could be mistaken for a normative requirement.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1110)

get timeouts: remove non-normative introduction

---

webdriver-spec.html

This drops the informational paragraph describing the Set Timeouts
command because it can easily be mistaken for a normative requirement.
It also makes some other, minor editorial fixups.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1111)

set timeouts: drop informational paragraph and small fixups

---

webdriver-spec.html

The first paragraph describing the Get Current URL command is
self-explanatory and can be surmised from the command's name.  To not
cause confusion about whether it is normative or informational,
it is removed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1113)

get current url: drop informational paragraph

---

webdriver-spec.html

The patch makes the first paragraph describing the semantics of
the command non-normative, because it could easily be mistaken for
a normative requirement.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1114)

back: make description non-normative

---

webdriver-spec.html

The first paragraph can be mistaken for a normative requirement.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1117)

get title: make introduction non-normative

---

webdriver-spec.html

"of element" is needless.
Fixes: https://github.com/w3c/webdriver/issues/1102
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1122)

pointer-interactable paint tree: remove erranous mention of element

---

webdriver-spec.html

x and y should come from the input state and not the action object since passing in x and y values in the payload of a pointerUp doesn't really make sense :)
cc/ @jgraham 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1139)

Change dispatch pointerUp's x, y handling

---

webdriver-spec.html

There's two ways CSS implementations are allowed to define lengths: they can either make 1 CSS pixel equal to the CSS reference pixel or they can make 1 CSS cm equal to 1 SI cm. We shouldn't care which they do.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1163)

Refer to "CSS pixels" not "CSS reference pixels"

---

webdriver-spec.html

Following the discussion in #1035, converted the `url variables` to a dictionary, that now has its own definition, that is passed along `parameters` to the remote end steps.
Nothing changes in the way remote end steps get values from `parameters` (`getting a property`).
Example: in [12.4 Find Element From Element](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-find-element-from-element#x12.4-find-element-from-element) a step says:
> Let start node be the result of trying to get a known connected element with argument element id. 
Before this change "element id" was used without any other references, as it is considered a named argument to the remote end steps.
After this change the remote end steps do not receive named parameters, such as "element id" in the example. So I was …

Pass url variables as a dictionary to the remote end steps (#1035)

---

webdriver-spec.html

Contrary to the note, they aren't proprietary, and have been in CSSOM View all the way back to its first draft a decade ago (see https://github.com/w3c/csswg-drafts/commit/fdd7f32848f891251bffd7134c004f783bf6e970).
Also add a note to the Set Window Rect resizing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1162)

Refer to Window.outerWidth/outerHeight normatively

---

webdriver-spec.html

In the definition for [extracting the script arguments from a request](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-extract-the-script-arguments-from-a-request) for Execute Script, we refer to a `script` variable, but it has not been defined. Presumably it is meant to match a `script`  property in the parameters?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1127)

add definition of 'script' variable

---

webdriver-spec.html

The way that I read this section, we are saying that the _result_ of this command should match the _result_ of `bot.dom.getVisibleText`, not that the _steps_ of the former should be analogous to the _result_ of the latter. But perhaps I am wrong!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1125)

clarify wording for Get Element Text algorithm

---

webdriver-spec.html

Usually we talk about where we are getting properties from. Presumably it is from `parameters` here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1130)

clarify where the 'scroll' property comes from in Take Element Screenshot

---

webdriver-spec.html

It is not currently clear what WebDriver should do when
document.activeElement returns null, which may happen if the document
element is deleted.  This makes it clear that it will return a no
such element error in such a case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1157)

get active element: return error if activeElement is null

---

webdriver-spec.html

The Element Clear command currently _resets_ interactable elements to their default value, e.g. what was defined in the `value` IDL attribute in the case of `<input>`. The intention of this command is to _clear_ the value entirely. These patches fixes the problem, but unfortunately had to reorganise dependencies a bit to make it happen.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1156)

element clear: clear instead of resetting elements

---

webdriver-spec.html

Drops the non-normative introductions that can be confusing to
implementors from the Delete Cookie and Delete All Cookies commands.
Fixes: https://github.com/w3c/webdriver/issues/1147
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1149)

cookies: remove non-normative introductions

---

webdriver-spec.html

WebIDL recently introduced dedicated syntax for mixins [1]. This
replaces the existing [NoInterfaceObject] and "implements" syntax with
"interface mixin" and "includes" in the appropriate places.
This fixes #1140 issue.
Test: https://github.com/w3c/web-platform-tests/pull/8770
***
<a href="https://pr-preview.s3.amazonaws.com/romandev/webdriver/pull/1176.html" title="Last updated on Dec 21, 2017, 10:09 AM GMT (8008572)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1176/8d89e8f...romandev:8008572.html" title="Last updated on Dec 21, 2017, 10:09 AM GMT (8008572)">Diff</a>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1176)

Use Web IDL's new-ish interface mixins concept

---

webdriver-spec.html

The facilities offered for protocol extensions are intended to be used
by both web standards and browser vendors. Prior to the application of
this commit, the specification text inconsistently described these two
distinct use cases [1]. The mechanism itself was biased towards the
"browser vendor" use case because it required the specification of an
"extension command prefix" which is not appropriate for all "web
standards" use cases [2].
Explicitly describe both use cases in the informative text and
generalize the normative text to better-support extensions by web
standards.
[1] https://github.com/w3c/webdriver/issues/1142
[2] https://github.com/w3c/webdriver/issues/1170
---
This is an attempt to resolve gh-1142 and gh-1170 as [recently discussed on …

Generalize protocol extension mechanism

---

implementation-report.md

Who knows which order the `[]` and `()` need to be in markdown? Also point at the living spec results, since otherwise the implementation report points at a raw HTML blob.

Fix link to current HTML results

---

webdriver-spec.html

WebDriver currently toggles the selectedness state of <option
disabled> elements.  Because we can interact with the containing
<select> element we should simulate the mouse interaction steps but
prevent it from changing the selectedness state.
Fixes: https://github.com/w3c/webdriver/issues/1187

element click: prevent selectedness change on <option disabled>

---

webdriver-spec.html

Please see the [associated bug](https://github.com/w3c/webdriver/issues/1193) for context and read each individual commit message.
Fixes https://github.com/w3c/webdriver/issues/1193.
***
<a href="https://pr-preview.s3.amazonaws.com/andreastt/webdriver/pull/1196.html" title="Last updated on Jan 15, 2018, 9:08 PM GMT (5ba4f48)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1196/981a0fe...andreastt:5ba4f48.html" title="Last updated on Jan 15, 2018, 9:08 PM GMT (5ba4f48)">Diff</a>

element clear: check for validity state and selected file length

---

webdriver-spec.html

This means that the session will fail if any capabilities can't be
merged, rather than failing only if the capabilities that can't be merged
are before the ones that are selected. The early failure is consistent
with the early failure for other kinds of validation errors elsewhere.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1204.html" title="Last updated on Jan 23, 2018, 2:00 PM GMT (fa4d3d1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1204/877030f...fa4d3d1.html" title="Last updated on Jan 23, 2018, 2:00 PM GMT (fa4d3d1)">Diff</a>

Try to merge capabilities before selecting them.

---

webdriver-spec.html

Defined in ECMA:
https://www.ecma-international.org/ecma-262/6.0/#sec-number.max_safe_integer
Closes #1202
***
<a href="https://pr-preview.s3.amazonaws.com/carlosgcampos/webdriver/pull/1210.html" title="Last updated on Jan 25, 2018, 2:57 PM GMT (2be6e8b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1210/980cbaf...carlosgcampos:2be6e8b.html" title="Last updated on Jan 25, 2018, 2:57 PM GMT (2be6e8b)">Diff</a>

Limit timeout and cookie expiry time values to the maximum safe integer

---

webdriver-spec.html

The navigator.webdriver WebIDL attribute is currently only meant
to be exposed when the webdriver-active flag is true.  Safari and
Edge expose the attribute unconditionally, and Gecko plans to follow
suit.
Making the attribute selectively present, which is unlike any other
web features are implemented, forces web authors to detect automation
in the following way:
var underAutomation = ("webdriver" in navigator) ? navigator.webdriver : false;
Following this patch, web authors can do this:
var underAutomation = navigator.webdriver;
Fixes: https://github.com/w3c/webdriver/issues/1214
***
<a href="https://pr-preview.s3.amazonaws.com/andreastt/webdriver/pull/1219.html" title="Last updated on Feb 2, 2018, 8:00 PM GMT (c9a12ed)">Preview</a> | <a …

interface: expose navigator.webdriver unconditionally

---

webdriver-spec.html

Small fixup to a224627 because webdriver-active is a flag, not a
boolean.
***
<a href="https://pr-preview.s3.amazonaws.com/andreastt/webdriver/pull/1220.html" title="Last updated on Feb 3, 2018, 3:34 PM GMT (e62ea8e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1220/a224627...andreastt:e62ea8e.html" title="Last updated on Feb 3, 2018, 3:34 PM GMT (e62ea8e)">Diff</a>

interface: webdriver-active flag is not a boolean

---

webdriver-spec.html

***
<a href="https://pr-preview.s3.amazonaws.com/andreastt/webdriver/pull/1221.html" title="Last updated on Feb 6, 2018, 2:08 PM GMT (97ec338)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1221/3b6ccb7...andreastt:97ec338.html" title="Last updated on Feb 6, 2018, 2:08 PM GMT (97ec338)">Diff</a>

interface: fix WebIDL links after ReSpec 19.1.1 release

---

webdriver-spec.html

British English spellings were unharmed.
***
<a href="https://pr-preview.s3.amazonaws.com/burg/webdriver/pull/1224.html" title="Last updated on Feb 12, 2018, 7:01 PM GMT (0d8a233)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1224/62e73ee...burg:0d8a233.html" title="Last updated on Feb 12, 2018, 7:01 PM GMT (0d8a233)">Diff</a>

Fix miscellaneous misspellings.

---

webdriver-spec.html

This PR is a continuation of https://github.com/w3c/webdriver/issues/1105 to remove/improve/adapt command descriptions that could be mistaken as normative.
***
<a href="https://pr-preview.s3.amazonaws.com/andreastt/webdriver/pull/1231.html" title="Last updated on Feb 21, 2018, 4:28 PM GMT (32317d7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1231/976387e...andreastt:32317d7.html" title="Last updated on Feb 21, 2018, 4:28 PM GMT (32317d7)">Diff</a>

Remove normative descriptions

---

webdriver-spec.html

***
<a href="https://pr-preview.s3.amazonaws.com/andreastt/webdriver/pull/1235.html" title="Last updated on Feb 26, 2018, 5:30 PM GMT (6522798)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1235/13c488e...andreastt:6522798.html" title="Last updated on Feb 26, 2018, 5:30 PM GMT (6522798)">Diff</a>

handling errors: remove unused invalid coordinates error

---

webdriver-spec.html

Fixes: https://github.com/w3c/webdriver/issues/1236
***
<a href="https://pr-preview.s3.amazonaws.com/andreastt/webdriver/pull/1237.html" title="Last updated on Mar 1, 2018, 1:40 PM GMT (1ded01a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1237/7438d6c...andreastt:1ded01a.html" title="Last updated on Mar 1, 2018, 1:40 PM GMT (1ded01a)">Diff</a>

user prompts: add missing stacktrace field to example

---

webdriver-spec.html

The element not selectable error is not used in any commands.
***
<a href="https://pr-preview.s3.amazonaws.com/andreastt/webdriver/pull/1250.html" title="Last updated on Apr 8, 2018, 3:28 PM GMT (a1760c6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1250/582ae36...andreastt:a1760c6.html" title="Last updated on Apr 8, 2018, 3:28 PM GMT (a1760c6)">Diff</a>

handling errors: drop element not selectable

---

results/html/all.html
results/html/analysis.css
results/html/complete-fails.html
results/html/consolidated.json
results/html/less-than-2.html
results/ie11.json

This change updates the ie11.json file to include the results from
https://gist.github.com/jimevans/2f8e6b3138bd771647cc711848d0609b,
and updates the https://w3c.github.io/webdriver/results/html content
(regenerated from running wptreport with the updated ie11.json file).

Add updated test results for IEDriver

---

webdriver-spec.html

**NOTE** This PR is intended to spark discussion. It touches on at least two issues already filed against the spec (#1153 and #1135), and should be considered, since user prompt handlers was largely removed from the Level 1 specification.
Section 18 of the spec states that, "When a user prompt appears, it is
the task of the subsequent command to handle it." The algorithm for
"Executing a function body" (Section 15.2) violates this statement,
insisting that the user prompt handler be invoked during the current
command, rather than by the subsequent command. Instead, we should
immediately abort the execute[Async]Script command, and let the subsequent
command handle the user prompt, if any.
***
<a href="https://pr-preview.s3.amazonaws.com/jimevans/webdriver/pull/1248.html" title="Last …

Updating prompt handling during user script to be consistent

---

webdriver-spec.html

***
<a href="https://pr-preview.s3.amazonaws.com/whimboo/webdriver/pull/1254.html" title="Last updated on Apr 19, 2018, 8:04 AM GMT (6251332)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1254/da5f9e8...whimboo:6251332.html" title="Last updated on Apr 19, 2018, 8:04 AM GMT (6251332)">Diff</a>

Remove extra "or" from beforeunload handler section

---

index.html

Change "existing users Selenium WebDriver" to "existing users of Selenium WebDriver".

Trivial grammatical fix (missing preposition)

---

index.html

As given by the HTML spec the `<input type=file>` element sends both the `input` and `change` event. The spec currently only requires to fire the `input` event.
https://html.spec.whatwg.org/#file-upload-state-(type=file):event-input-3
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file
Testcase: https://output.jsbin.com/vijukozuro/1

Element Send Keys for "<input type=file>" has to also send a change event.

---

implementation-report.md

The link for Firefox was a manual "this content has moved to.." redirect to this bugzilla dependency tree page, so this just skips that.
For the link for Edge, I usually had to do some clicking around on the platform status page before I could finally get to the MS docs page with the implementation details for Webdriver in Edge, so this link just goes directly there.
Thanks!

More direct links to implementation docs for Firefox and Edge

---

index.html

ReSpec defaults to the gh-pages branch, whereas we serve ours from
master.

correct github branch meta info

---

index.html

Changes the default value of the user prompt handler to "dismiss
and notify", which is effectively what null evaluates to through
the handler's treatment of the missing value default state.
By making the user prompt handler not be an enumerated attribute,
we can remove the "missing value default state" and "not in the
table of simple dialogs" cases when running the handling code.
This change makes the capability behave like other similar capabilities
such as pageLoadStrategy, where the matched/negotiated value is
returned when the session is created.
Fixes: https://github.com/w3c/webdriver/issues/1276

user prompt handler: stop pretending it is an enumerated attribute

---

index.html

Whilst it is logically correct to use 408 for the timeout and script
timeout errors, it causes a collision with HTTP semantics implement
in HTTP clients.  To support Keep-Alive we allow retries in HTTP
clients and if a client sees code 408 it thinks that the server has
gone away and retries the request.
This causes Execute Script, Navigate To, and Refresh commands to
be sent twice with some HTTP clients.
This is a backwards incompatible change to WebDriver in order to
not break HTTP/1.1 Keep-Alive.
Fixes: https://github.com/w3c/webdriver/issues/1287

errors: change timeout errors from 408 to 500 HTTP status code

---

index.html

Fixes #1191. @shs96c mind reviewing this change?
Tests will be written via https://bugzilla.mozilla.org/show_bug.cgi?id=1473814.
Thanks.
***
<a href="https://pr-preview.s3.amazonaws.com/whimboo/webdriver/pull/1303.html" title="Last updated on Sep 21, 2018, 11:47 AM GMT (108c7d0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1303/831dc6f...whimboo:108c7d0.html" title="Last updated on Sep 21, 2018, 11:47 AM GMT (108c7d0)">Diff</a>

Element Click and Element Clear need to handle user prompts (#1191)

---

index.html

Console message about "Linter (local-refs-exist): Broken local reference
found in document" and #dom-navigatorautomationinformation

Fix Respec warning

---

index.html

The characters "}" and "]" appears to be mixed up in the table of
shifted characters.
Thanks-to: @pyfisch
Fixes: https://github.com/w3c/webdriver/issues/1313

shifted character: fix mixup of ] and }

---

index.html

The clear algorithm for <input> uses a list to tell the drivers what
to do.  The last condition, "if the type attribute's current state
defines one" seems like another item to this list but is actually
a logic condition for the preceding sentence, "and then invoke the
value sanitization algorithm".
This turns it into a logical condition using "if-and-only-if".

clear algorithm: value sanitization should be done when type attribute is defined

---

index.html

Quoting the commit message of the last patch:
> Calculating the centre point of a square may produce a decimal
> precision number.  Given a 1x1 px square the center point will be
> (0.5,0.5), but the DOM operates in integer CSS pixels.
> 
> Rounding the number would get us the closest positive integer, or 1. 
> However, the coordinate (1,1) is beyond the bounding box of the
> square.
> 
> This means we need to floor the number to ensure we always get a
> click point that is within the client rect of the element.
> 
> An additional complexity is that not all web platform APIs treat
> floating point numbers the same way.  DOMElement.elementsFromPoint,
> which we use for getting the paint tree to determine if the web
> element is interactable, will floor the number which deems the
> element …

Make in-view center point CSS pixel aware

---

index.html

In chapter 10. Command Contexts, section 10.3 Switch To Window:
> Return success with date null.
Return success with data null.

Minor wording fix

---

index.html

WebDriver’s JSON serialisation algorithm doesn’t handle all the collection types handled by implementations found in the wild. These are:
* Arguments
* FileList
* HTMLAllCollection
* HTMLFormControlsCollection
* HTMLOptionsCollection
Whilst adding these I also discovered that the algorithm didn’t really inspect the interior of array-like collections at all, so the PR also fixes that. This is effectively mirroring how geckodriver handles JSON currently. See each commit message for more detailed information, since I also fixed a few other minor bugs along the way.
Tests for this can be found in https://github.com/web-platform-tests/wpt/blob/master/webdriver/tests/execute_script/collections.py.
This was discovered whilst reviewing https://github.com/web-platform-tests/wpt/pull/13880.

Fix collection serialization and support collection types found in the wild

---

index.html

This is a high-level reorganisation of the document's chapters.
Most notably, all element related commands are moved into a single
chapter ("Elements"), with subchapters for Interactability, Retrieval,
State, and Interaction.
Various other chapter names have been shortened, which gives a
simpler look to the table of contents and way of referencing the
specification.
There are no functional changes apart from editorial fixups in this
patch.

Reorganise chapters

---

index.html

We can mark a section with the "informative" CSS class to have
ReSpec automatically mark it as non-normative.
***
<a href="https://pr-preview.s3.amazonaws.com/andreastt/webdriver/pull/1358.html" title="Last updated on Nov 19, 2018, 10:08 AM GMT (17c1195)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1358/d494784...andreastt:17c1195.html" title="Last updated on Nov 19, 2018, 10:08 AM GMT (17c1195)">Diff</a>

design: use respec informative builtin

---

index.html

See each individual commit message.
(Please don’t squash to keep these preserved.)
***
<a href="https://pr-preview.s3.amazonaws.com/andreastt/webdriver/pull/1356.html" title="Last updated on Nov 20, 2018, 10:47 AM GMT (31e491c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1356/9667a8b...andreastt:31e491c.html" title="Last updated on Nov 20, 2018, 10:47 AM GMT (31e491c)">Diff</a>

Move index of definitions to end of document

---

index.html

We don't have to reference RFC4122 three times in one paragraph.
Once at the end lends much better readability.
***
<a href="https://pr-preview.s3.amazonaws.com/andreastt/webdriver/pull/1365.html" title="Last updated on Nov 20, 2018, 1:14 PM GMT (b3484b5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1365/12589b5...andreastt:b3484b5.html" title="Last updated on Nov 20, 2018, 1:14 PM GMT (b3484b5)">Diff</a>

terminology: reduce number of normative references to RFC4122

---

index.html

Strings should be formatted with the quotes outside the <code> tag
so that it is clear to the reader the quote marks are not part of
the string itself, like this:
"<code>foo</code>"
This patch comes along with a few editorial changes, such as the
removal of unnecessary commas in logical groupings, some table
simplification, and indentation changes as a result of breaking up
the text.  Although overall, there were no larger functional changes
made in this patch.
***
<a href="https://pr-preview.s3.amazonaws.com/andreastt/webdriver/pull/1366.html" title="Last updated on Nov 20, 2018, 3:15 PM GMT (a69f73a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1366/6d31f89...andreastt:a69f73a.html" title="Last updated on Nov 20, 2018, 3:15 PM GMT (a69f73a)">Diff</a>

fix strings throughout

---

index.html

This swaps the Conformance and Design chapters, so that Design comes
before defining the remainder of the specification.  This harmonises
better with how other specifications are written.
***
<a href="https://pr-preview.s3.amazonaws.com/andreastt/webdriver/pull/1364.html" title="Last updated on Nov 20, 2018, 3:17 PM GMT (11c7cd2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1364/9053e5a...andreastt:11c7cd2.html" title="Last updated on Nov 20, 2018, 3:17 PM GMT (11c7cd2)">Diff</a>

Swap Design and Conformance chapters

---

index.html

As ReSpec now recognises the Living Document status and correctly
marks it as "W3C Living Document", we can drop our own custom
subtitle.
***
<a href="https://pr-preview.s3.amazonaws.com/andreastt/webdriver/pull/1367.html" title="Last updated on Nov 22, 2018, 12:01 PM GMT (95fcf30)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1367/caec5c9...andreastt:95fcf30.html" title="Last updated on Nov 22, 2018, 12:01 PM GMT (95fcf30)">Diff</a>

drop subtitle

---

index.html

This change is editorial.  The current definition of readiness state
is quite clunky to read because of the excessively loaded match
statement.  This simplifies it somewhat and improves the language.
***
<a href="https://pr-preview.s3.amazonaws.com/andreastt/webdriver/pull/1368.html" title="Last updated on Nov 22, 2018, 12:08 PM GMT (80c171a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1368/0ccf553...andreastt:80c171a.html" title="Last updated on Nov 22, 2018, 12:08 PM GMT (80c171a)">Diff</a>

nodes: improve flow of readiness state

---

index.html

Remote ends steps are run against all types of remote ends, not
just browsers.
***
<a href="https://pr-preview.s3.amazonaws.com/andreastt/webdriver/pull/1369.html" title="Last updated on Nov 22, 2018, 12:10 PM GMT (7d03761)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1369/33271cb...andreastt:7d03761.html" title="Last updated on Nov 22, 2018, 12:10 PM GMT (7d03761)">Diff</a>

commands: correct definition of remote end steps

---

index.html

Arguments is technically not a prototype, and the test is for the
toString result.
Relates to https://github.com/w3c/webdriver/issues/1347.
***
<a href="https://pr-preview.s3.amazonaws.com/andreastt/webdriver/pull/1352.html" title="Last updated on Nov 22, 2018, 1:17 PM GMT (9757c87)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1352/8dc9cc7...andreastt:9757c87.html" title="Last updated on Nov 22, 2018, 1:17 PM GMT (9757c87)">Diff</a>

collection: check for "Arguments" string

---

index.html

The WebDriver specification is normative in its descriptions, and no
longer depends on RFC2119, and in particular its capitalised styling
of MUST, SHOULD, RECOMMENDED, MAY, et al.
This patch largely retains the words, but de-capitalises them.  In a
few cases it rewrites the sentence to make better sense in English.
***
<a href="https://pr-preview.s3.amazonaws.com/andreastt/webdriver/pull/1370.html" title="Last updated on Nov 22, 2018, 1:27 PM GMT (06c2caf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1370/ab32fb3...andreastt:06c2caf.html" title="Last updated on Nov 22, 2018, 1:27 PM GMT (06c2caf)">Diff</a>

get rid of legacy RFC2119 style

---

index.html

This adds an endpoint at /session/<session id>/window/new that opens a
new top-level browsing context. This takes a single parameter "type"
that is used as a hint as to the kind of window to create within the
application. The return value includes the handle of the new window and
the type of the window that was created.
Fixes https://github.com/w3c/webdriver/issues/1138
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1324.html" title="Last updated on Nov 22, 2018, 5:58 PM GMT (b9160cd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1324/be19393...b9160cd.html" title="Last updated on Nov 22, 2018, 5:58 PM GMT (b9160cd)">Diff</a>

Add a endpoint for creating a new window.

---

index.html

The HTTP Method for Create Window command was specified
as POST at https://w3c.github.io/webdriver/#endpoints,
but as GET at https://w3c.github.io/webdriver/#create-window.
Since this command takes a parameter, it needs to use POST method.
***
<a href="https://pr-preview.s3.amazonaws.com/JohnChen0/webdriver/pull/1377.html" title="Last updated on Dec 5, 2018, 3:46 PM GMT (ee20967)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1377/de3aadf...JohnChen0:ee20967.html" title="Last updated on Dec 5, 2018, 3:46 PM GMT (ee20967)">Diff</a>

Fix HTTP Method for Create Window

---

index.html

Several key values in key code table are inconsistent with other tables,
and also are in conflict with other entries in the same table.
***
<a href="https://pr-preview.s3.amazonaws.com/JohnChen0/webdriver/pull/1384.html" title="Last updated on Dec 27, 2018, 11:29 PM UTC (90af629)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1384/6f4ce2c...JohnChen0:90af629.html" title="Last updated on Dec 27, 2018, 11:29 PM UTC (90af629)">Diff</a>

Fix inconsistency in key code table

---

index.html

Fixes #1387.
***
<a href="https://pr-preview.s3.amazonaws.com/whimboo/webdriver/pull/1388.html" title="Last updated on Jan 7, 2019, 7:52 PM UTC (820c2a6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1388/31483b0...whimboo:820c2a6.html" title="Last updated on Jan 7, 2019, 7:52 PM UTC (820c2a6)">Diff</a>

"Switch To Frame" has to raise "invalid argument" error for invalid frame id types (#1387)

---

index.html

Fixes #1389.
***
<a href="https://pr-preview.s3.amazonaws.com/whimboo/webdriver/pull/1390.html" title="Last updated on Jan 9, 2019, 11:47 AM UTC (f81dc1b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1390/a56962c...whimboo:f81dc1b.html" title="Last updated on Jan 9, 2019, 11:47 AM UTC (f81dc1b)">Diff</a>

"Switch To Frame" has to raise "invalid argument" error for out of bounds frame id number values (#1389)

---

.travis.yml
Makefile

respec is broken upstream, so this will temporarily disable it so
we can land specification changes.

make, travis: disable respec testing

---

index.html

This is a complete rewrite of the way user-configurable timeouts
are handled in WebDriver.  The prose that is currently in the
specification does not work, or indeed make any sense.
This rewrite is in the spirit of the intention of the Working Group.
***
<a href="https://pr-preview.s3.amazonaws.com/andreastt/webdriver/pull/1394.html" title="Last updated on Jan 30, 2019, 3:33 PM UTC (0e1617e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1394/5b686d2...andreastt:0e1617e.html" title="Last updated on Jan 30, 2019, 3:33 PM UTC (0e1617e)">Diff</a>

timeouts: rewrite

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/JohnChen0/webdriver/pull/1397.html" title="Last updated on Feb 9, 2019, 12:12 AM UTC (30b3525)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1397/b16bbbd...JohnChen0:30b3525.html" title="Last updated on Feb 9, 2019, 12:12 AM UTC (30b3525)">Diff</a>

Fix link to fragment serializing algorithm

---

index.html

As currently worded, the response's value may be double
JSON-encoded, which is far from ideal. We also fail to
state that the bytes must be UTF-8 encoded.
***
<a href="https://pr-preview.s3.amazonaws.com/shs96c/webdriver-1/pull/1404.html" title="Last updated on Mar 21, 2019, 12:04 AM UTC (c41c371)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1404/4280c91...shs96c:c41c371.html" title="Last updated on Mar 21, 2019, 12:04 AM UTC (c41c371)">Diff</a>

Clarify how a response is constructed.

---

index.html

Adding the `id="conformance"` tells ReSpec tells ReSpec that "diagrams, examples, and notes in this specification are non-normative, as are all sections explicitly marked non-normative."
ReSpec then intelligently classifies your references, without requiring "!".
***
<a href="https://pr-preview.s3.amazonaws.com/marcoscaceres/webdriver/pull/1418.html" title="Last updated on May 2, 2019, 11:35 AM UTC (15e733a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1418/9b93d7e...marcoscaceres:15e733a.html" title="Last updated on May 2, 2019, 11:35 AM UTC (15e733a)">Diff</a>

chore: fix ReSpec warnings

---

index.html

Consistently reference the `null` keyword via its definition and using a
`<code>` tag.
This patch was generated programatically using the following command:
perl -pe 's/(<var>|<a>)+null(<\/var>|<\/a>)+/<a><code>null<\/code><\/a>/g' index.html
***
<a href="https://pr-preview.s3.amazonaws.com/bocoup/webdriver/pull/1422.html" title="Last updated on May 11, 2019, 1:27 AM UTC (56d05c9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1422/b7c6791...bocoup:56d05c9.html" title="Last updated on May 11, 2019, 1:27 AM UTC (56d05c9)">Diff</a>

Normalize treatement of `null` keyword

---

index.html

In the JSON internal clone algorithm (#dfn-internal-json-clone-algorithm),
there is an "Otherwise" statement that is not preceded by an "if".
This is likely leftover line that was not deleted when web-element
cloning was moved later in the algorithm.
***
<a href="https://pr-preview.s3.amazonaws.com/rohpavone/webdriver/pull/1420.html" title="Last updated on May 3, 2019, 10:21 PM UTC (465f98a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1420/b7c6791...rohpavone:465f98a.html" title="Last updated on May 3, 2019, 10:21 PM UTC (465f98a)">Diff</a>

Remove old JSON web-element clone line

---

index.html

@andreastt based on your comment in #1445 I went through and looked for all of the times "matching" was used to refer to Strings. Let me know if any of these shouldn't be changed. Also, I'm unsure about https://github.com/w3c/webdriver/blob/master/index.html#L7133 but I think it is ok as is.
***
<a href="https://pr-preview.s3.amazonaws.com/titusfortner/webdriver/pull/1451.html" title="Last updated on Oct 15, 2019, 7:38 PM UTC (7066cca)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1451/3216584...titusfortner:7066cca.html" title="Last updated on Oct 15, 2019, 7:38 PM UTC (7066cca)">Diff</a>

matching is not defined for strings

---

index.html

Enable the Respec feature for automatic injection of MDN annotations, as documented at https://github.com/w3c/respec/wiki/mdn
Currently, this causes MDN annotations to be added for the following: CloseWindow, GetElementAttribute, GetElementProperty, GetElementTagName, GetTimeouts, GetWindowHandles, GetWindowRect, SetTimeouts, SetWindowRect, navigator.webdriver
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1446.html" title="Last updated on Sep 27, 2019, 3:15 AM UTC (4f61fb0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1446/3216584...4f61fb0.html" title="Last updated on Sep 27, 2019, 3:15 AM UTC (4f61fb0)">Diff</a>

Editorial: Enable MDN annotations

---

index.html

change URL from seleniumhq.org to selenium.dev
***
<a href="https://pr-preview.s3.amazonaws.com/manoj9788/webdriver/pull/1472.html" title="Last updated on Dec 15, 2019, 5:00 PM UTC (1910376)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1472/f462670...manoj9788:1910376.html" title="Last updated on Dec 15, 2019, 5:00 PM UTC (1910376)">Diff</a>

update url to new site

---

index.html

This patch defines the same site property for cookies as requested in:
- https://github.com/w3c/webdriver/issues/1134
- https://github.com/w3c/webdriver/issues/1304
- https://github.com/webdriverio/webdriverio/issues/4893
I couldn't find a key for same site defined in the [RFC 6265](https://tools.ietf.org/html/rfc6265) spec but the property exist in [the spec draft](https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-03#page-27) which will make RFC 6265 obsolete.
Chrome implements this behavior as of version 80. Firefox has them available to test and will be making them default behaviors in the future. Edge also plans to change its default behaviors.
Further read on same site cookies: https://web.dev/samesite-cookies-explained/
***
<a …

Define same site cookie property

---

index.html

There is already a similar description for Back command, so this makes them both consistent.
***
<a href="https://pr-preview.s3.amazonaws.com/OndraM/webdriver/pull/1476.html" title="Last updated on Dec 21, 2019, 2:08 PM UTC (836f234)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1476/146f63b...OndraM:836f234.html" title="Last updated on Dec 21, 2019, 2:08 PM UTC (836f234)">Diff</a>

navigation: extend description of Forward

---

index.html

Change spelling from samesite to sameSite, to be more consistent with
other property keys.
***
<a href="https://pr-preview.s3.amazonaws.com/JohnChen0/webdriver/pull/1477.html" title="Last updated on Dec 23, 2019, 8:28 PM UTC (7fe8848)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1477/146f63b...JohnChen0:7fe8848.html" title="Last updated on Dec 23, 2019, 8:28 PM UTC (7fe8848)">Diff</a>

Change JSON key for Cookie same site property

---

index.html

The definition used for which form control elements not to use the
actions API for is rather sketchy because it includes inline examples
in a match guard.
This change attempts to formalise the definition of non-typeable
form controls.  It also includes a new example section to guide
implementors, since the definition is rather weak (since we can't
tell UAs how to represent anything.)
***
<a href="https://pr-preview.s3.amazonaws.com/andreastt/webdriver/pull/1471.html" title="Last updated on Dec 11, 2019, 2:52 PM UTC (739d00d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1471/f462670...andreastt:739d00d.html" title="Last updated on Dec 11, 2019, 2:52 PM UTC (739d00d)">Diff</a>

Define non-typeable form controls more exhaustively

---

index.html

This is apparently something that people use automation for rather often, so there should be a cross-browser solution for it.
The featureset is based on what's common in browsers and is close to what CDP offers, without the control over headers and footers, which I propose to defer until we have some experience implementing this more basic featureset.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1468.html" title="Last updated on Dec 11, 2019, 11:55 AM UTC (16fd8ee)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1468/f462670...16fd8ee.html" title="Last updated on Dec 11, 2019, 11:55 AM UTC (16fd8ee)">Diff</a>

Add support for outputting a paginated document as PDF

---

index.html

Issue #1245 points out that you cannot pass data parameters to a
GET method request, so it is currently impossible to pass a "scroll"
field to Take Element Screenshot.
It was also discovered in the discussion that no vendors implement
this feature.  Because we want the specification to match reality,
this patch removes the "scroll" field for Take Element Screenshot.
Fixes: https://github.com/w3c/webdriver/issues/1245
***
<a href="https://pr-preview.s3.amazonaws.com/andreastt/webdriver/pull/1249.html" title="Last updated on Apr 6, 2018, 3:40 PM GMT (81c89fa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1249/582ae36...andreastt:81c89fa.html" title="Last updated on Apr 6, 2018, 3:40 PM GMT (81c89fa)">Diff</a>

take element screenshot: drop scroll feature

---

index.html

CSSOM-View has removed the behaviour from ScrollIntoView dictionary.
This change updates to remove it from our scroll and means that browsers
should default to `auto` as described in CSSOM-View. Fixes #1449
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1493.html" title="Last updated on Mar 27, 2020, 10:49 AM UTC (0e22ed1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1493/4265381...0e22ed1.html" title="Last updated on Mar 27, 2020, 10:49 AM UTC (0e22ed1)">Diff</a>

Remove scroll behavior so it uses default.

---

index.html

The Infra Spec has started calling JavaScript Strings Strings in
https://github.com/whatwg/infra/pull/292 and this aligns the webdriver
spec with that. Fixes #1486
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1492.html" title="Last updated on Mar 27, 2020, 10:41 AM UTC (fcfacc2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1492/4265381...fcfacc2.html" title="Last updated on Mar 27, 2020, 10:41 AM UTC (fcfacc2)">Diff</a>

Update String reference to match WHATWG infra spec

---

README.md

WebDriver Level 1 was published as a W3C Recommendation.

readme: change status of Level 1

---

index.html

Documentation of this mechanism:
https://github.com/w3c/respec/wiki/localBiblio
While in the area, update to the latest draft version.
***
<a href="https://pr-preview.s3.amazonaws.com/foolip/webdriver/pull/1507.html" title="Last updated on May 28, 2020, 12:06 PM UTC (2a9aa47)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1507/f66dd0e...foolip:2a9aa47.html" title="Last updated on May 28, 2020, 12:06 PM UTC (2a9aa47)">Diff</a>

Define RFC6265bis in `localBiblio`

---

index.html

"GitHub w3c/webdriver" is linked at the top, and "GitHub Issues" soon after
the remove sentence in the (generated) "Status of This Document".
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1511.html" title="Last updated on May 29, 2020, 9:57 AM UTC (d96fb61)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1511/ee190be...d96fb61.html" title="Last updated on May 29, 2020, 9:57 AM UTC (d96fb61)">Diff</a>

Remove redundant pointer to GitHub repo

---

index.html

These are issues discovered by Bikeshed, but the fixes can be applied to
the current spec as well, to make the future conversion smaller.
***
<a href="https://pr-preview.s3.amazonaws.com/foolip/webdriver/pull/1515.html" title="Last updated on May 29, 2020, 1:23 PM UTC (ae64edc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1515/f019306...foolip:ae64edc.html" title="Last updated on May 29, 2020, 1:23 PM UTC (ae64edc)">Diff</a>

Fix mistaken use and typos with <var>

---

index.html

…ole of elements
Fixes #1439
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1444.html" title="Last updated on May 29, 2020, 3:15 PM UTC (580edd3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1444/f66dd0e...580edd3.html" title="Last updated on May 29, 2020, 3:15 PM UTC (580edd3)">Diff</a>

Add support for calculating the accessible label and the accessible role of elements

---

index.html

Discovered while converting to Bikeshed but also affects ReSpec:
- data-lt=go and data-lt="input type state" don't work since
there's no matching <dfn>.
- data-lt=perform-actions doesn't make sense, the "Perform Actions"
section isn't the intended target.
- Duplicate "Resettable element" definition
- Broken canvas width/height links
***
<a href="https://pr-preview.s3.amazonaws.com/foolip/webdriver/pull/1518.html" title="Last updated on Jun 1, 2020, 12:15 PM UTC (1f3cdb4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1518/162e738...foolip:1f3cdb4.html" title="Last updated on Jun 1, 2020, 12:15 PM UTC (1f3cdb4)">Diff</a>

Fix various minor mishaps with <dfn> and <a>

---

index.html

These are both unused definitions before this change:
https://w3c.github.io/webdriver/#dfn-browser-chrome
https://w3c.github.io/webdriver/#dfn-browser-chrome-element
***
<a href="https://pr-preview.s3.amazonaws.com/foolip/webdriver/pull/1520.html" title="Last updated on Jun 2, 2020, 8:22 AM UTC (a8e332e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1520/33c1f38...foolip:a8e332e.html" title="Last updated on Jun 2, 2020, 8:22 AM UTC (a8e332e)">Diff</a>

Link the browser chrome (elements) definitions

---

index.html

Discovered as part of https://github.com/w3c/webdriver/issues/1462.
It doesn't matter in ReSpec because the <section> nesting level is used,
but Bikeshed does not use the HTML outline algorithm:
https://tabatkins.github.io/bikeshed/#table-of-contents
***
<a href="https://pr-preview.s3.amazonaws.com/foolip/webdriver/pull/1521.html" title="Last updated on Jun 2, 2020, 9:28 AM UTC (5e45041)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1521/df1d9bd...foolip:5e45041.html" title="Last updated on Jun 2, 2020, 9:28 AM UTC (5e45041)">Diff</a>

Fix h1-6 levels to match section nesting / ToC

---

index.html

This adds the concept of "additional webdriver capabilites" which are
those defined by other specifications. Each capability has a name and
provides validation and (optionaly) matching algorithms to enable to
to participate in the capabilities processing steps.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1523.html" title="Last updated on Jun 2, 2020, 1:35 PM UTC (0ef033a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1523/cebfd28...0ef033a.html" title="Last updated on Jun 2, 2020, 1:35 PM UTC (0ef033a)">Diff</a>

Add hooks for other specs to define WebDriver capabilities.

---

index.html

A few of these result in warnings about links inside links with
Bikeshed, but normalize all of them to the same style.
Drive-by lt->data-lt and wrapping of page visibility terms.
***
<a href="https://pr-preview.s3.amazonaws.com/foolip/webdriver/pull/1524.html" title="Last updated on Jun 2, 2020, 3:27 PM UTC (dbc9dce)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1524/4c58fec...foolip:dbc9dce.html" title="Last updated on Jun 2, 2020, 3:27 PM UTC (dbc9dce)">Diff</a>

Normalize markup in definitions index

---

index.html

The hook allows other specs to get access to the session and the
capabilities immediately before the new session response is sent to
the local end. This allows them to set up any state that is connected
to the session, and update the value of any capabilities they own in
the response.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1527.html" title="Last updated on Jun 4, 2020, 8:13 AM UTC (8e92a48)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1527/a953788...8e92a48.html" title="Last updated on Jun 4, 2020, 8:13 AM UTC (8e92a48)">Diff</a>

Add a hook immediately before a new session is created

---

index.html

<dfn>NavigatorAutomationInformation</dfn> was unused and results in a
warning when converting to Bikeshed.
Use a style closer to the "ideal linking setup" instead:
https://github.com/w3c/respec/wiki/WebIDL-Guide
data-dfn-for/data-link-for are no longer needed with this setup.
***
<a href="https://pr-preview.s3.amazonaws.com/foolip/webdriver/pull/1526.html" title="Last updated on Jun 2, 2020, 7:15 PM UTC (fb68e5c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1526/4c58fec...foolip:fb68e5c.html" title="Last updated on Jun 2, 2020, 7:15 PM UTC (fb68e5c)">Diff</a>

Tweak IDL definition style to avoid unused <dfn>

---

index.html

Both [DOM-PARSING] and [DOMPARSING] were referenced, and the latter
resolved to https://domparsing.spec.whatwg.org/, which doesn't exist.
***
<a href="https://pr-preview.s3.amazonaws.com/foolip/webdriver/pull/1525.html" title="Last updated on Jun 2, 2020, 6:06 PM UTC (90f1eb6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1525/4c58fec...foolip:90f1eb6.html" title="Last updated on Jun 2, 2020, 6:06 PM UTC (90f1eb6)">Diff</a>

Consolidate the DOM Parsing and Serialization references

---

index.html

Should be height instead of width
***
<a href="https://pr-preview.s3.amazonaws.com/k7z45/webdriver/pull/1532.html" title="Last updated on Jun 9, 2020, 11:54 PM UTC (d6e01e3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1532/4217382...k7z45:d6e01e3.html" title="Last updated on Jun 9, 2020, 11:54 PM UTC (d6e01e3)">Diff</a>

Fix typo from width to height in print description

---

index.html

The linked specs and the wpt tests all show values being capitalized
***
<a href="https://pr-preview.s3.amazonaws.com/titusfortner/webdriver/pull/1535.html" title="Last updated on Jul 16, 2020, 4:02 AM UTC (3d3e39d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1535/536adfe...titusfortner:3d3e39d.html" title="Last updated on Jul 16, 2020, 4:02 AM UTC (3d3e39d)">Diff</a>

SameSite values should be capitalized

---

index.html

The current Webdriver Actions API’s pointer source types have three input types: "mouse", "pen", and "touch". For the three pointer type, it only supports actions of "pointerDown", "pointerUp", "pointerMove" and "pointerCancel". We cannot generate a mouse wheel scroll from the current source types and actions. We want to add a new source type to generate wheel events to support testing wheel scroll or zoom on web pages.
The design doc is 
https://docs.google.com/document/d/1AzPkvexzuUJ1SF-6pZFpnn2lwEYlk3T0e-Wi52UWFZ4/
WPT tests:
https://cs.chromium.org/chromium/src/third_party/blink/web_tests/external/wpt/uievents/order-of-events/mouse-events/wheel-scrolling-manual.htm
https://cs.chromium.org/chromium/src/third_party/blink/web_tests/external/wpt/uievents/order-of-events/mouse-events/wheel- …

Add wheel source type to WebDriver Actions API Spec

---

index.html

Previously the parent and top-level browsing contexts were computed
properties based on the current browsing context. This fails in the
case where the frame containing the current browsing context is
removed from the DOM tree since the browsing context is then discarded
meaning that trying to compute its parents will fail. In practice we
expect operations working with the top-level browsing context to
continue working in that case (and indeed implementations are
mostly/entirely not following the current spec), so this makes the
top-level and parent browsing contexts explictly stored properties of
the session that are updated at the point where we change browsing
contexts.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1543.html" title="Last updated on Sep 8, 2020, …

Store the top-level and parent browsing contexts explicitly.

---

index.html

Fixes issue #1403.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1548.html" title="Last updated on Sep 22, 2020, 11:50 AM UTC (ee89e83)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1548/afc3d5d...ee89e83.html" title="Last updated on Sep 22, 2020, 11:50 AM UTC (ee89e83)">Diff</a>

Allow maximum safe integer for timeout values (#1403)

---

index.html

Fixes issue #1544.
@jgraham or someone else, can you please review? Thanks
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1556.html" title="Last updated on Oct 16, 2020, 12:26 PM UTC (da1275a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1556/99f7ced...da1275a.html" title="Last updated on Oct 16, 2020, 12:26 PM UTC (da1275a)">Diff</a>

Fix browsing context checks for Switch To Parent Frame when already the top-level browsing context

---

index.html

This PR contains the spec prose for commands for retrieving an element's shadow root, and finding a single and multiple elements from that shadow root. This approach was agreed to in principle during the TPAC (virtual) F2F sessions.
***
<a href="https://pr-preview.s3.amazonaws.com/jimevans/webdriver/pull/1565.html" title="Last updated on Jan 11, 2021, 2:21 PM UTC (3e40fe0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1565/5ab304e...jimevans:3e40fe0.html" title="Last updated on Jan 11, 2021, 2:21 PM UTC (3e40fe0)">Diff</a>

Support Shadow DOM

---

index.html

This is the light version of #1552 that keeps implementation effort for browser vendors low while enabling intermediary nodes the ability to create async sessions in a lightweight way. There are two new endpoints being added in this patch:
1. __Get Session__
Returns the capabilities of an active session. This is also very useful for endpoint nodes
in the scenario where a clients wants to attach to an active session receive the capabilities
it has attached to. This information is not necessarily given for client implementations.
2. __Async New Session__
Endpoint nodes run the same session creation steps as in New session but return only the
session id. Intermediary nodes keep a list of "session creation jobs" that maps "session
creation job ids" to session ids of active sessions.
Now the …

Add Get Session and Async New Session

---

index.html

Fixes issue #1153.
I took the words as @jgraham proposed given that it seems to describe the expected behavior best. @AutomatedTester if you think it needs further tweaking please let me know.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1572.html" title="Last updated on Feb 17, 2021, 11:52 AM UTC (6f59a7c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1572/8315393...6f59a7c.html" title="Last updated on Feb 17, 2021, 11:52 AM UTC (6f59a7c)">Diff</a>

Clarify immediate script abortion when user prompt appears.

---

index.html

This change to the protocol was made a bit prematurely.
At Sauce Labs we have evaluated the implementation details
after the change and found lots of improvements to be made.
Therefor I propose to revert this and come back when we have
found a better solution to this.
Revert "add unknown session error"
This reverts commit 83153937210ef5e797ee03cb4124b4fcb883f8bb.
Revert "make responses between endpoint and intermediary node conform"
This reverts commit 96790d52d672acb5407ef20ef7597abc30fe9870.
Revert "add get session and async new session"
This reverts commit c83c8f0cef5bf06bcf12708c0e240b1fb574da41.
***
<a href="https://pr-preview.s3.amazonaws.com/webdriver/webdriver/pull/1576.html" title="Last updated on Mar 9, 2021, 3:00 PM UTC (2fb6155)">Preview</a> | <a …

Revert "Add Get Session and Async New Session"

---

index.html

The term "context object" is being removed from DOM:
https://github.com/whatwg/dom/pull/973
This also changes a reference to <a> elements to the string "a", since
querySelectorAll's argument is a string. This may have unintended side
effects of matching <svg:a> and "a" elements in other namespaces.
***
<a href="https://pr-preview.s3.amazonaws.com/foolip/webdriver/pull/1582.html" title="Last updated on Apr 19, 2021, 12:57 PM UTC (25e9da1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1582/35df53a...foolip:25e9da1.html" title="Last updated on Apr 19, 2021, 12:57 PM UTC (25e9da1)">Diff</a>

Editorial: migrate from "context object" to "this"

---

index.html

The problem seemed to be that Respec expected [[Foo]] internal methods
to be associated with a WebIDL interface, which they aren't because
they're in ECMAScript.
The somewhat hacky workaround is to use the ECMAScript type they're
defined on as the interface name like `Object.[[Put]]` in place of
`[[Put]]`. This doesn't seem ideal, but it at least fixes the errors,
and the intent is still understandable.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1617.html" title="Last updated on Sep 16, 2021, 11:45 AM UTC (55eccae)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1617/d8556ca...55eccae.html" title="Last updated on Sep 16, 2021, 11:45 AM UTC (55eccae)">Diff</a>

Fix Respec errors

---

index.html

Fixes issue #1591.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1612.html" title="Last updated on Sep 6, 2021, 6:20 PM UTC (a30683b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1612/3c94c9c...a30683b.html" title="Last updated on Sep 6, 2021, 6:20 PM UTC (a30683b)">Diff</a>

Update contentEditable link to official draft.

---

index.html

The Permissions API is looking to add a Web Driver extension. However, the spec is currently missing these exports for us to do the integration.
Blocks: https://github.com/w3c/permissions/pull/346
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1639.html" title="Last updated on Feb 14, 2022, 5:58 AM UTC (22bd73d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1639/1917e89...22bd73d.html" title="Last updated on Feb 14, 2022, 5:58 AM UTC (22bd73d)">Diff</a>

Editorial: export definitions needed for Permissions API

---

index.html

This ensures that multiple commands can't simultaneously access the
same input state, in a way that would cause races.
The spec uses a synchronous wait, on the assumption that higher layers
are either serializing commands, or are already running their steps in
parallel, so it's not blocking the "main thread".
This requires any use of actions to go via "dispatch actions" rather
than calling the individual dispatch endpoints, so we need to refactor
some commands that are defined in terms of the actions they create.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1650.html" title="Last updated on Mar 24, 2022, 3:37 PM UTC (3822426)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1650/b3519fd...3822426.html" title="Last updated on Mar 24, 2022, …

Serialize actions dispatch

---

index.html

We were previously vauge about how pointer input sources correspond to
pointer ids. With this change we directly specify how to compute the
pointerId property that's used on Pointer Events.
This also allows us to stop passing the input id into dispatch
algorithms, since it's no longer used.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1651.html" title="Last updated on Apr 6, 2022, 7:15 PM UTC (e085e20)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1651/3b443f4...e085e20.html" title="Last updated on Apr 6, 2022, 7:15 PM UTC (e085e20)">Diff</a>

Fix assigning a pointer id in actions

---

index.html

Fix for issue #1662. @shs96c please let me know what you think. Thanks.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1663.html" title="Last updated on Jun 14, 2022, 11:23 AM UTC (272ca52)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1663/a99633b...272ca52.html" title="Last updated on Jun 14, 2022, 11:23 AM UTC (272ca52)">Diff</a>

Merge "get a known element" into "get a known connected element"

---

index.html

This means that the state is not shared between different
tabs/windows. In the current model it's still per-session, although it
would be easy to change (in the spec) to be per-browser if we think
that it fundamentally leaks too much between different sessions to be
meaningfully separate.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1654.html" title="Last updated on Jun 22, 2022, 4:36 PM UTC (5142dd8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1654/3b443f4...5142dd8.html" title="Last updated on Jun 22, 2022, 4:36 PM UTC (5142dd8)">Diff</a>

Make input state per top-level browsing context

---

index.html

Prevously we allowed these properties to be undefined, and then later
tried to do computations on the values. That doesn't work; they either
need to have an integer default value or require that a value is
supplied.
Since implementations currently seem to raise an exception for these
values being undefined, the easiest approach is to require that they
are supplied, so that's what's implemented here.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1676.html" title="Last updated on Jul 25, 2022, 2:28 PM UTC (b5e4651)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1676/e3b112f...b5e4651.html" title="Last updated on Jul 25, 2022, 2:28 PM UTC (b5e4651)">Diff</a>

Require pointerMove and wheel coordinates to be integers

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1673.html" title="Last updated on Sep 22, 2022, 9:32 PM UTC (8823aea)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1673/3a11903...8823aea.html" title="Last updated on Sep 22, 2022, 9:32 PM UTC (8823aea)">Diff</a>

Update atoms sha

---

index.html

This does just enough to make the build pass for the navigable changes in HTML, without actually fixing the underlying model to match.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1704.html" title="Last updated on Dec 16, 2022, 9:01 PM UTC (96f1b0c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1704/0a24679...96f1b0c.html" title="Last updated on Dec 16, 2022, 9:01 PM UTC (96f1b0c)">Diff</a>

Fix build for HTML changes

---

index.html

Generalise Element and ShadowRoot storage
For WebDriver BiDi we want to be able to return any Node object, and
to support all reachable Nodes, not just those in the same browsing
context. Therefore the approach of having per-Window Element and
ShadowRoot caches won't work. Instead implement the following:
* A per session, per browsing context group Node to id mapping that
can store any Node.
* Frontends in WebDriver to store Elements and ShadowRoots in this
map, and perform the additional same-document, connected element,
checks that the protocol requires.
This doesn't introduce any normative changes into WebDriver, it just
refactors the infrastructure to make it reusable in the BiDi context.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1705.html" title="Last …

Node cache

---

index.html

This specification relies on the term "response" as defined by the Fetch standard. The "error" type which is returned by fallible algorithms does not qualify as such a response. This makes the use of the phrase "error response" to define the "error" type somewhat confusing.
Replace "error response" with the more generic "error value" to avoid insinuating a non-existent relationship.
***
<a href="https://pr-preview.s3.amazonaws.com/bocoup/webdriver/pull/1710.html" title="Last updated on Jan 3, 2023, 10:49 PM UTC (7c743be)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1710/6c3b67a...bocoup:7c743be.html" title="Last updated on Jan 3, 2023, 10:49 PM UTC (7c743be)">Diff</a>

Replace misleading term

---

index.html

If we've previously seen an element in the current window, but it was GC'd we should return "stale element reference". To support this, add a set of seen node ids to each Window, so we can check if the element is stale.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1707.html" title="Last updated on Jan 6, 2023, 11:35 AM UTC (e30204d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1707/6c3b67a...e30204d.html" title="Last updated on Jan 6, 2023, 11:35 AM UTC (e30204d)">Diff</a>

Fix returning stale element reference

---

index.html

Currently in step 2 of [clone an object](https://w3c.github.io/webdriver/#dfn-clone-an-object) only the own enumerable properties are taken into account. This actually causes issues with WebIDL interfaces like `File` which won't get the `name` property serialized.
Interestingly we have a [specific wdspec test for a `FileList` case](https://github.com/web-platform-tests/wpt/blob/231ddb37db93e1e837faeebf058e72d5ae2a5285/webdriver/tests/execute_async_script/collections.py#L28-L48), which requires the `name` property serialized. And [all browsers are currently passing this test](https://wpt.fyi/results/webdriver/tests/execute_async_script/collections.py?label=master&product=firefox%5Bexperimental%5D&product=chrome%5Bexperimental%5D&product=edge%5Bexperimental%5D&product=safari&aligned&view=sub …

Improve handling of objects and collections in "internal JSON clone algorithm"

---

index.html

This is really designed for BiDi, allowing actions to specify the
origin relative to an element in the form:
{
type: "element"
sharedId: <id>
}
rather than sending in a WebDriver-style element reference. For
simplicit this allows the new construct to work irrespective of
whether actions are being used in a HTTP session or a BiDi
session (but a BiDi session is not expected to support the HTTP-style
web element reference identifiers).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1653.html" title="Last updated on Dec 22, 2022, 4:35 PM UTC (24e4604)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1653/6c3b67a...24e4604.html" title="Last updated on Dec 22, 2022, 4:35 PM UTC (24e4604)">Diff</a>

Add the Element Origin concept

---

index.html

Regression from #1712.
Edit: The issue here is that by copying and pasting in the other PR I accidentally used the term `is stale` instead of `is detached` for detached checks when deserializing ShadowRoot references.
@jgraham can you please review?
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1714.html" title="Last updated on Jan 19, 2023, 12:26 PM UTC (39c13da)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1714/80b6d5d...39c13da.html" title="Last updated on Jan 19, 2023, 12:26 PM UTC (39c13da)">Diff</a>

Fix detached check for "get a known shadow root" step

---

index.html

Correct the markup so the build system recognizes the reference to the variable named "keyup action" and add a period to end the statement.
***
<a href="https://pr-preview.s3.amazonaws.com/bocoup/webdriver/pull/1721.html" title="Last updated on Mar 2, 2023, 3:20 AM UTC (3dd448b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1721/883ea38...bocoup:3dd448b.html" title="Last updated on Mar 2, 2023, 3:20 AM UTC (3dd448b)">Diff</a>

Fix typos in algorithm for Element Send Keys

---

index.html

Update error in [get a known shadow root](https://www.w3.org/TR/webdriver/#dfn-get-a-known-shadow-root) algorithm from [no such element](https://www.w3.org/TR/webdriver/#dfn-no-such-element) to [no such shadow root](https://pr-preview.s3.amazonaws.com/lutien/webdriver/pull/1726.html#dfn-no-such-shadow-root).
***
<a href="https://pr-preview.s3.amazonaws.com/lutien/webdriver/pull/1726.html" title="Last updated on Mar 15, 2023, 2:20 PM UTC (e15bce2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1726/a638d46...lutien:e15bce2.html" title="Last updated on Mar 15, 2023, 2:20 PM UTC (e15bce2)">Diff</a>

Fix error in "get a known shadow root" algorithm

---

index.html

Right now the `DOMTokenList` is not handled as collection and as such falls back to an arbitrary object. 
The serialization results in an empty object to be returned because there are no enumerable properties. To actually allow `Get Element Property` to return the `classList` it needs to be handled as a collection.
***
<a href="https://pr-preview.s3.amazonaws.com/whimboo/webdriver/pull/1728.html" title="Last updated on Mar 20, 2023, 5:31 PM UTC (3bbccc1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1728/a638d46...whimboo:3bbccc1.html" title="Last updated on Mar 20, 2023, 5:31 PM UTC (3bbccc1)">Diff</a>

Add "DOMTokenList" to collections

---

index.html

It seems like in [validation algorithm](https://w3c.github.io/webdriver/#dfn-validate-capabilities), we should use `capabilities` instead `capability` similar to other algorithms in this section.
***
<a href="https://pr-preview.s3.amazonaws.com/lutien/webdriver/pull/1745.html" title="Last updated on Jun 6, 2023, 6:29 AM UTC (f247c19)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1745/a638d46...lutien:f247c19.html" title="Last updated on Jun 6, 2023, 6:29 AM UTC (f247c19)">Diff</a>

Rename "capability" to "capabilities" in validation algorithm

---

index.html

The existing link was self-referential.  This was unhelpful for understanding the document.
***
<a href="https://pr-preview.s3.amazonaws.com/tomgilligan/webdriver/pull/1752.html" title="Last updated on Aug 4, 2023, 10:33 AM UTC (b74a693)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1752/441e433...tomgilligan:b74a693.html" title="Last updated on Aug 4, 2023, 10:33 AM UTC (b74a693)">Diff</a>

Fix link for page loading strategy

---

index.html

The term was renamed in the HTML spec in whatwg/html#8712 so the current reference was broken as mentioned in #1735.
While here, use ReSpec's shorthand syntax to refer to these sub concepts directly and avoid having to specifically link to them in the index at the end of the document.
***
<a href="https://pr-preview.s3.amazonaws.com/rakuco/webdriver/pull/1750.html" title="Last updated on Aug 7, 2023, 9:27 AM UTC (7679754)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1750/866fedb...rakuco:7679754.html" title="Last updated on Aug 7, 2023, 9:27 AM UTC (7679754)">Diff</a>

editorial: Use "content navigable" instead of "nested navigable"

---

README.md

In this commit we update the Safari vendor status document to point to the set of commands supporting the W3C WebDriver protocol. The previous link redirects to [macOS WebDriver Commands for Safari 11.1 and earlier](https://developer.apple.com/documentation/webkit/macos_webdriver_commands_for_safari_11_1_and_earlier?language=objc), which highlights the WebDriver Commands supporting the Selenium JSON Wire Protocol instead.

Point Apple Safari Vendor status to W3C WebDriver protocol supported commands

---

index.html

Short term fix for issue #1758 to raise a specific failure for unsupported origin types in `get coordinates relative to an origin`.
***
<a href="https://pr-preview.s3.amazonaws.com/whimboo/webdriver/pull/1760.html" title="Last updated on Sep 5, 2023, 9:08 PM UTC (f19c38a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1760/d9be1ae...whimboo:f19c38a.html" title="Last updated on Sep 5, 2023, 9:08 PM UTC (f19c38a)">Diff</a>

Raise "unsupported operation" error when "pointer" is used as origin for key and wheel input sources

---

index.html

coordindates -> coordinates
***
<a href="https://pr-preview.s3.amazonaws.com/aprotyas/webdriver/pull/1762.html" title="Last updated on Sep 22, 2023, 8:58 PM UTC (e345780)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1762/35a868a...aprotyas:e345780.html" title="Last updated on Sep 22, 2023, 8:58 PM UTC (e345780)">Diff</a>

Fix "coordinates" typo in pointer input source description

---

index.html

While implementing the serialization of window and frame objects I noticed that there are no deserialization steps available for these two object types.
***
<a href="https://pr-preview.s3.amazonaws.com/whimboo/webdriver/pull/1738.html" title="Last updated on Aug 7, 2023, 10:26 AM UTC (3775811)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1738/866fedb...whimboo:3775811.html" title="Last updated on Aug 7, 2023, 10:26 AM UTC (3775811)">Diff</a>

Add deserialization steps for web frame and web window

---

index.html

The key codes for `\uE00B`, `\uE03D`, `\uE053` are either incorrect or missing. The key code for `\uE019` should be `NumpadEqual` to distinguish it from `=`.
See https://github.com/web-platform-tests/wpt/pull/40122 for tests
On the two major platforms (macOS and Windows), we have:
- `=` has the code value `NumpadEqual` for the numpad value.
- `Pause` has the code value `Pause`
This is on a US-layout extended keyboard.
- https://www.w3.org/TR/uievents-code/
- https://www.w3.org/TR/uievents-key/
***
<a href="https://pr-preview.s3.amazonaws.com/jrandolf/webdriver/pull/1740.html" title="Last updated on Jul 24, 2023, 1:11 PM UTC (9e37f98)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1740/a65f9fb...jrandolf:9e37f98.html" title="Last updated on Jul 24, 2023, 1:11 PM …

Update key codes

---

index.html

element click is erroneously defined as `«pointer move action, pointer down action, pointer move action».` but should obviously be `«pointer move action, pointer down action, pointer up action».` making use of the pointer up action defined
***
<a href="https://pr-preview.s3.amazonaws.com/dten/webdriver/pull/1779.html" title="Last updated on Dec 13, 2023, 10:24 AM UTC (337f29f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1779/e91f9d8...dten:337f29f.html" title="Last updated on Dec 13, 2023, 10:24 AM UTC (337f29f)">Diff</a>

Correct element click actions list

---

index.html

To properly check an element for `disabled` we have to reference the `actually disabled` section of the HTML spec. 
It means the link changes from https://html.spec.whatwg.org/#concept-fe-disabled to https://html.spec.whatwg.org/#concept-element-disabled.
@jgraham can you please review?
***
<a href="https://pr-preview.s3.amazonaws.com/whimboo/webdriver/pull/1769.html" title="Last updated on Nov 20, 2023, 4:05 PM UTC (5e44158)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1769/35a868a...whimboo:5e44158.html" title="Last updated on Nov 20, 2023, 4:05 PM UTC (5e44158)">Diff</a>

Fix reference for element disabled

---

index.html

This specification uses the List type from WHATWG Infra [1]. It does so indirectly, working with a derivative which it refers to as a "JSON List." This type is not defined, but because its usage matches that of the List, the qualifier "JSON" appears to be superfluous.
Remove the qualifier to clarify the type of the specification values.
[1] https://infra.spec.whatwg.org/#lists
***
<a href="https://pr-preview.s3.amazonaws.com/bocoup/webdriver/pull/1748.html" title="Last updated on Jun 28, 2023, 2:01 AM UTC (76df041)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1748/441e433...bocoup:76df041.html" title="Last updated on Jun 28, 2023, 2:01 AM UTC (76df041)">Diff</a>

Editorial: remove inaccurate qualifier

---

index.html

Right now the spec says that we should automatically dismiss any `beforeunload` prompt upon navigation or window close:
> [User prompts](https://w3c.github.io/webdriver/#dfn-user-prompts) that are spawned from [beforeunload](https://w3c.github.io/webdriver/#dfn-beforeunload) event handlers, are [dismissed](https://w3c.github.io/webdriver/#dfn-dismissed) implicitly upon [navigation](https://w3c.github.io/webdriver/#dfn-navigating) or [close window](https://w3c.github.io/webdriver/#dfn-close-window), regardless of the defined [user prompt handler](https://w3c.github.io/webdriver/#dfn-user-prompt-handler).
But the problem is the definition of `dismissed`:
> To dismiss the [current user prompt](https://w3c.github.io/webdriver/#dfn-current-user-prompt), do so as if the user would click the …

Automatically accept any "beforeunload" prompt upon navigation or close window.

---

index.html

This is a large change, but it's almost entirely refactoring.
The main aim here is to split the session concept so that there's a base "session" which holds the session id and state that's appropriate to both WebDriver classic and BiDi. Then, we define a "HTTP Session" as one that has the HTTP Flag set and use that to compose-in any state that's only used in the classic HTTP-based protocol.
In addition, we rework the way state is passed around the spec so that we are using an explicit session object, rather than making use of a global "current session". This makes things clearer if we allow the possibility of multiple non-HTTP sessions.
There is also a bit of cleanup in the way we pass other variables around, and in the capabilites processing.
***
<a …

Refactor session handling for better integration with BiDi

---

index.html

This makes editing much easier, since unpaired ' were causing syntax highlighting problems. It also standardizes on a single kind of apostrophe character rather than the mix we had before.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1801.html" title="Last updated on Mar 5, 2024, 11:34 AM UTC (3123161)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1801/63a397f...3123161.html" title="Last updated on Mar 5, 2024, 11:34 AM UTC (3123161)">Diff</a>

Replace ' and ´ with &apos;

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1713.html" title="Last updated on Jan 11, 2023, 10:09 AM UTC (245b5df)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1713/714bd27...245b5df.html" title="Last updated on Jan 11, 2023, 10:09 AM UTC (245b5df)">Diff</a>

Add definition for "weak map"

---

index.html

This takes us down to zero respec warnings when bulding the spec.
We still have terms which are only referenced in non-normative contexts. That's probably also a bug, and could be fixed in a followup. However this at least provides a clean baseline for future spec work.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1805.html" title="Last updated on Mar 7, 2024, 6:45 PM UTC (48a3ef8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1805/52c3e3a...48a3ef8.html" title="Last updated on Mar 7, 2024, 6:45 PM UTC (48a3ef8)">Diff</a>

Fix unreferenced definitions

---

index.html

This refactors the way that timeout configuration is used in the spec, and fixes several bugs, but does not otherwise have intentional normative changes.
The main change is the creation of a "timeouts configuration" struct that is owned by the session. A new struct is created when the timeouts are changed (including during capabilities processing) and this fixes a number of confusing cases where the "JSON deserialize" algorithm was linked in place of the more specific algorithm for reading the timeout data.
In addition a new "timer" class is created with a flag that's set when the required time has elapsed. This is now used in all places where we wait up to a timeout, and we assume we're able to wait for the flag to change, or check the current value of the flag, as required. Fixing this …

Fix timeouts configuration

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1791.html" title="Last updated on Mar 11, 2024, 4:01 PM UTC (6a39106)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1791/6c86972...6a39106.html" title="Last updated on Mar 11, 2024, 4:01 PM UTC (6a39106)">Diff</a>

User prompt handler capabilities

---

index.html

Selenium's atom "Is Element Enabled" special-cases the disabled state for "option" and "optgroup" elements when the nearest anchestor "select" is disabled as well.
@jgraham please let me know if that is what you would imagine based on your comment from:
https://bugzilla.mozilla.org/show_bug.cgi?id=1863266#c12
***
<a href="https://pr-preview.s3.amazonaws.com/whimboo/webdriver/pull/1807.html" title="Last updated on Apr 16, 2024, 12:51 PM UTC (8f951ba)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1807/43903d0...whimboo:8f951ba.html" title="Last updated on Apr 16, 2024, 12:51 PM UTC (8f951ba)">Diff</a>

Clarify when an element is disabled

---

index.html

It was not intended to add a new `userPromptHandler` capability. Instead the existing `unhandledPromptBehavior` capability got enhanced for WebDriver BiDi.
***
<a href="https://pr-preview.s3.amazonaws.com/whimboo/webdriver/pull/1808.html" title="Last updated on Apr 10, 2024, 9:24 AM UTC (ade93c7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1808/43903d0...whimboo:ade93c7.html" title="Last updated on Apr 10, 2024, 9:24 AM UTC (ade93c7)">Diff</a>

Fix inappropriate usage of "userPromptHandler" as capability name

---

index.html

With PR #1791 we got extended support for the `unhandledPromptBehavior` landed which added a new Object type to define handlers for all the prompt handlers more granularly.
While implementing the capability handling for that new type in Firefox I noticed a couple of issue. This PR fixes these and also updates some cases to make it better understandable what specific variables actually are.
FYI @sadym-chromium @nechaev-chromium @gsnedders for when you get started to implement these changes in the drivers.
Updated tests will be part of my work on https://bugzilla.mozilla.org/show_bug.cgi?id=1895738.
***
<a href="https://pr-preview.s3.amazonaws.com/whimboo/webdriver/pull/1812.html" title="Last updated on May 21, 2024, 9:01 PM UTC (76573d3)">Preview</a> | <a …

Fix issues with User Prompt Handler after PR #1791

---

index.html

This would prevent creating a BiDi session for a browser that already has a HTTP session with the notify flag set for some prompt handler.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1818.html" title="Last updated on Jun 14, 2024, 9:53 AM UTC (d95609c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1818/34f9efa...d95609c.html" title="Last updated on Jun 14, 2024, 9:53 AM UTC (d95609c)">Diff</a>

Don't require user prompt handler notify to match when creating session

---

index.html

Fixes https://github.com/w3c/webdriver/issues/1821
***
<a href="https://pr-preview.s3.amazonaws.com/katranci/webdriver/pull/1822.html" title="Last updated on Jun 28, 2024, 11:39 AM UTC (ba144ba)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1822/0d759c9...katranci:ba144ba.html" title="Last updated on Jun 28, 2024, 11:39 AM UTC (ba144ba)">Diff</a>

Fix typo for "specficiations" in Sessions section

---

index.html

Incorrect parameter name "input state" was replaced with "source"
***
<a href="https://pr-preview.s3.amazonaws.com/ChernyshevDS/webdriver/pull/1820.html" title="Last updated on Jun 27, 2024, 8:25 AM UTC (930aed7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1820/0d759c9...ChernyshevDS:930aed7.html" title="Last updated on Jun 27, 2024, 8:25 AM UTC (930aed7)">Diff</a>

Fixed parameter name in "Dispatch a pointer down action" paragraph

---

index.html

* Make string valued handlers only set the alert/confirm/prompt modals, but object valued handlers with a `default` key set the default for all prompt types including `beforeUnload`
* Unconditionally return the user prompt handler in the new session response
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1819.html" title="Last updated on Jun 14, 2024, 9:55 AM UTC (add07f9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1819/34f9efa...add07f9.html" title="Last updated on Jun 14, 2024, 9:55 AM UTC (add07f9)">Diff</a>

Update user prompt handler configuration

---

index.html

Previously it was unclear if it was acceptable to return without error from set window rect if the implementation is unable to set some of the properties.
This updates the spec so that:
* It's unambiguously OK to run the command even if you don't support some aspects of the functionality on the current platform / configuration (you are expected to continue to return an error if you don't support any aspect of the functionality).
* It's clear that both position and dimension properties are best effort, and even if you are able to adjust them there's no guarantee that you get the exact requested values.
* It's clear what to do if you get just an x coordinate but not y, or just width but not height, or vice-versa. Previously this was undefined.
***
<a …

Allow ignoring position or dimensions in set window rect

---

index.html

* Restore handling both missing and null values for parameters.
* Fix some grammar errors.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1832.html" title="Last updated on Jul 17, 2024, 1:55 PM UTC (ee975a4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1832/bb939cc...ee975a4.html" title="Last updated on Jul 17, 2024, 1:55 PM UTC (ee975a4)">Diff</a>

Fix some small problems with set window rect changes

---

index.html

- Update the note to reflect the fact that "default" now applies to before unload and mention fallbackDefault
- fix `get the prompt handler` to select fallbackDefault when relevant
***
<a href="https://pr-preview.s3.amazonaws.com/juliandescottes/webdriver/pull/1831.html" title="Last updated on Jul 19, 2024, 8:41 PM UTC (6058d03)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1831/af51973...juliandescottes:6058d03.html" title="Last updated on Jul 19, 2024, 8:41 PM UTC (6058d03)">Diff</a>

Update user prompt handler note for fallbackDefault

---

index.html

This PR aligns WebDriver classic with WebDriver BiDi and enforces a 1pt minimum page size for the Print command.
***
<a href="https://pr-preview.s3.amazonaws.com/juliandescottes/webdriver/pull/1843.html" title="Last updated on Oct 9, 2024, 12:39 PM UTC (f8760bb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1843/91b29b2...juliandescottes:f8760bb.html" title="Last updated on Oct 9, 2024, 12:39 PM UTC (f8760bb)">Diff</a>

Fix missing minimum print size in Print page command

---

index.html

Basically any single action could cause the current (top-level) browsing context to get closed eg. clicking or pressing a key for an element that calls `window.close()`. The following action in the sequence needs to fail with a `no such window` error.
I'm going to add tests for classic and BiDi over on https://bugzilla.mozilla.org/show_bug.cgi?id=1932916.
***
<a href="https://pr-preview.s3.amazonaws.com/whimboo/webdriver/pull/1861.html" title="Last updated on Nov 27, 2024, 3:48 PM UTC (c58363c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1861/db06684...whimboo:c58363c.html" title="Last updated on Nov 27, 2024, 3:48 PM UTC (c58363c)">Diff</a>

Raise "no such window" error in "dispatching actions" when browsing context (navigable) does no longer exist

---

index.html

Fixes #1837.
@jgraham could you please check? I hope that this is fine - it at least matches what we use in Firefox now when dispatching the actions from the parent process and it works fine. Thanks.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Dec 3, 2024, 3:19 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.
:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fraw.githubusercontent.com%2Fwhimboo%2Fwebdriver%2F34634ad5a49bd0567934e692b2f8222f41fafcfb%2Findex.html%3F …

Use actions queue when dispatching undo actions from "Release Actions"

---

index.html

Fixes #1855.
***
<a href="https://pr-preview.s3.amazonaws.com/whimboo/webdriver/pull/1865.html" title="Last updated on Dec 12, 2024, 10:05 AM UTC (f137936)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1865/7d8beb9...whimboo:f137936.html" title="Last updated on Dec 12, 2024, 10:05 AM UTC (f137936)">Diff</a>

Fix undefined variable "scriptResult" in remote steps of "Execute Async Script"

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/whimboo/webdriver/pull/1877.html" title="Last updated on Jan 31, 2025, 3:21 PM UTC (eb2ea89)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1877/9cb696c...whimboo:eb2ea89.html" title="Last updated on Jan 31, 2025, 3:21 PM UTC (eb2ea89)">Diff</a>

Fix perform and release actions for valid browsing context check and handle alert step

---

index.html

Fixes #1880.
@jgraham and @OrKoN can you please review? Thanks!
***
<a href="https://pr-preview.s3.amazonaws.com/whimboo/webdriver/pull/1881.html" title="Last updated on Feb 7, 2025, 3:04 PM UTC (d5a15a7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1881/78d3c9b...whimboo:d5a15a7.html" title="Last updated on Feb 7, 2025, 3:04 PM UTC (d5a15a7)">Diff</a>

Update "process pointer move action" to allow fractional numbers for x and y positions

---

index.html

Allow for `file` prompt type in capabilities.
Required for https://github.com/w3c/webdriver-bidi/pull/883.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1884.html" title="Last updated on Feb 25, 2025, 12:15 PM UTC (2b36293)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1884/a67669c...2b36293.html" title="Last updated on Feb 25, 2025, 12:15 PM UTC (2b36293)">Diff</a>

Allow `file` prompt type

---

index.html

Sorry but my ocd had to do it.
***
<a href="https://pr-preview.s3.amazonaws.com/GeorgiosVeropoulos/webdriver/pull/1896.html" title="Last updated on May 12, 2025, 9:01 PM UTC (26c1e65)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1896/6b43932...GeorgiosVeropoulos:26c1e65.html" title="Last updated on May 12, 2025, 9:01 PM UTC (26c1e65)">Diff</a>

Corrects the use of an before Number to a for proper grammar.

---

index.html

Fixes #1900.
https://github.com/w3c/webdriver-bidi/pull/932 is the WebDriver-BiDi equivalent.
***
<a href="https://pr-preview.s3.amazonaws.com/whimboo/webdriver/pull/1901.html" title="Last updated on Jun 11, 2025, 6:48 AM UTC (d3440ec)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1901/b8a7cdb...whimboo:d3440ec.html" title="Last updated on Jun 11, 2025, 6:48 AM UTC (d3440ec)">Diff</a>

Remove FTP proxy which is no longer supported by browsers

---

index.html

Previously, this points us to https://html.spec.whatwg.org/multipage/embedded-content.html#the-source-element
But it really means the variable. And it created a redundant entry "source element" in https://w3c.github.io/webdriver/#index-defined-elsewhere
***
<a href="https://pr-preview.s3.amazonaws.com/yezhizhen/webdriver/pull/1913.html" title="Last updated on Jul 17, 2025, 6:35 AM UTC (08bf809)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1913/3055808...yezhizhen:08bf809.html" title="Last updated on Jul 17, 2025, 6:35 AM UTC (08bf809)">Diff</a>

Fix wrong link for `source` in Dispatch Tick Actions
