w3c/webdriver

01_introduction.html
09_elements.html
10_element_state.html
webdriver-spec.html

Rewrite element displayed algorithm

---

02_commands.html

Fixes unexpected alert open and unknown method errors, as well as
some typos.

Correct JSON status strings

---

webdriver-spec.html

This takes the first rect and then gets the centre point of it.

Describe how to calculate hit point for clicks

---

webdriver-spec.html

This is a rewrite of all the find element(s) commands and rewrite of the css selector to show how it can be used.

Find elements

---

webdriver-spec.html

Implementations will have to make decisions about types, and in particular
sizes of the allocated variables.

Enforce size and type checks throughout

---

webdriver-spec.html

See https://github.com/w3c/webdriver/pull/314#issuecomment-233657561.

Return error on attempt to serialise stale element

---

webdriver-spec.html

This addresses the concern raised in #25418

Suggest browser specific extension in Protocol Extensions.

---

webdriver-spec.html

Use non-normative language in the Security appendix.

---

webdriver-spec.html

Add the basic infrastructure for actually dispatching actions, and
initial drafts of the implementation for keyboard and mouse actions.

Infrastructure for actions dispatch and implementation for null and key actions.

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/333)

Add a status endpoint.

---

webdriver-spec.html

No functional changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/330)

Lexicographically order UI Events definitions

---

issue.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/415)

Add colon before quote

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/343)

Define extension capabilities

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/345)

Always return response data in a value field

---

echidna-manifest.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/416)

Update Echnida manifest with issue.js

---

.travis.yml
publish

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/421)

Autopublish with Echnida on validation success

---

webdriver-spec.html

Fixes #422.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/423)

Make pointerMove duration optional

---

webdriver-spec.html

Little things I noticed while implementing the spec in Marionette. @jgraham r?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/428)

Make small corrections to Actions

---

webdriver-spec.html

This defines the details for setting a property and value on an Object.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/431)

Defining Setting a Property

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/334)

Allow status command to include optional arbitrary JSON fields

---

webdriver-spec.html

This is an action from a previous F2F.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/440)

Specify scrollIntoView arguments

---

webdriver-spec.html

Thanks to @Dzenly for fixing this!
Fixes #425.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/442)

Correct math for finding in-view centre point

---

webdriver-spec.html

PR includes some inline comments that ask for clarification -- these will be removed.
@jgraham @AutomatedTester r?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/443)

Correct dispatch of key actions.

---

webdriver-spec.html

Addresses #464
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/465)

Correct Typo

---

webdriver-spec.html

Not sure if this is something that is better to take place towards to final stages of writing the document.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/474)

Convert remote & local end occurences to <a>

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/478)

Add DOM spec dependency 'fire an event'

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/481)

Fix <a> data-lt value to match dfn

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/483)

Correct one <a> to <var> in cloning an object

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/484)

Correct 'clone algorithm' <a> to <var>

---

webdriver-spec.html

Getting a cookie name not a path
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/472)

update variable name to match what is in the list of endpoints

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/494)

Correct extension capability notation. Fixes #447

---

webdriver-spec.html

Closes #438.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/497)

Make when to use the session implicit wait timeout clear.

---

webdriver-spec.html

Closes #452
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/498)

Correct link to "Set Timeouts" command.

---

webdriver-spec.html

Closes issue #405
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/502)

Spell "dialogue" using the common US spelling.

---

webdriver-spec.html

Closes issue #419.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/490)

Add back the "tag name" element location strategy.

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/507)

Add missing dependency for HTML's Navigator object

---

webdriver-spec.html

The table is missing a header section and a <dfn> like the rest
of the tables.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/514)

Table of dispatch action algorithms: format table and reword text.

---

webdriver-spec.html

Closes issue #409
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/505)

Specify how to handle <input type='file' multiple='multiple'>

---

webdriver-spec.html

This does not completely define what to do (notably,
the events that should be fired are omitted) but puts
in place some of the specialised handling we need.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/510)

Start defining what to do in Element Click for OPTION elements.

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/517)

Link "getting a property" throughout the document. Fixes #453

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/519)

Fix <dfn> for option and data element, and new <dnf> optgroup element

---

webdriver-spec.html

Also converted related text to links
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/521)

Add missing HTML dependencies for area and map element

---

webdriver-spec.html

Also added 'unicode codepoint' links
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/520)

Add The Unicode Standard and dependency for 'codepoint'

---

webdriver-spec.html

Fixes part of https://github.com/w3c/webdriver/issues/529
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/530)

Make "switch" statements wording uniform

---

webdriver-spec.html

These are all I could spot for the moment. Also, some 'element'
links need to be converted to <var> but will do in another piece
of work.

Convert some 'element' to links

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/540)

Minor tag reformatting of some element related text

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/538)

Convert some <a> 'element' links to <var> in algorithms

---

webdriver-spec.html

This makes the algorithm more robust to future changes
in the specs we depend on, and also simplifies our text.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/534)

Update Element Clear and the definition of `editable`

---

webdriver-spec.html

Make this clearer. Closes issue #527.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/539)

There are two kinds of webdriver implementation and two node types.

---

webdriver-spec.html

This closes issue #357.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/541)

Unset keyboard modifiers before typing in `Element Send Keys`

---

webdriver-spec.html

But leave focus on the element.
This closes issue #404
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/542)

`Element Send Keys`: fire input event.

---

webdriver-spec.html

This closes issue #482.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/543)

Define `keyboard-interactable`

---

webdriver-spec.html

Fixes #522.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/546)

Remove a note that doesn't shed much light.

---

webdriver-spec.html

Fixes #528 
Fixes part of #529
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/547)

Reword and add step in 'delete cookie' algorithm

---

webdriver-spec.html

Closes #448.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/552)

Reference extension capabilities in the `Capabilities` section.

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/555)

Reference proxy configuration in the specification. Fixes #450

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/556)

Remove superfluous use of valid. It is either of that type or not.

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/557)

Link to insecure TLS certificates definition. Fixes #459

---

issue.js

Upgrades import of issue widget from https://github.com/andreastt/issue-widget.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/568)

Upgrade issue.js

---

webdriver-spec.html

Fixes https://github.com/w3c/webdriver/issues/564
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/570)

Unify usage of UI, UX elements to 'browser chrome elements'

---

webdriver-spec.html

Fixes https://github.com/w3c/webdriver/issues/550
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/572)

Reword 'element command' to just 'command'

---

webdriver-spec.html

Closes #383
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/559)

`Element Send Keys`: Ensure that uploaded files actually exist

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/577)

Fix get element property definition

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/582)

Correct typo: capabilties to capabilities

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/583)

Convert some 'HTTP status' to links

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/576)

Refactor description of element container and fix subtle bugs

---

webdriver-spec.html

Correct a mistake I created. Sorry for that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/590)

Correct typo 'an command' to 'a command'

---

webdriver-spec.html

Also convert a 'joint session history' to link
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/591)

Add missing dependency for HTML session history and links

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/592)

Correct links for DOM-PARSING dependencies

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/589)

Minor window rect fixes

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/594)

Correct typo top-leval to top-level

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/596)

Use document element to fullscreen by element

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/597)

Fix some actions typos

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/599)

Add reference to device state

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/601)

Make acknowledgements current and update lists of contributors

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/598)

Correct headings in corresponding input state type table

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/607)

Clean up respec errors around JSON

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/612)

Simplify text and link to html element

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/611)

Correct links for UI-EVENTS dependencies

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/614)

Reorder errors lexicographically and fix element click intercepted description

---

webdriver-spec.html

This is used to set the value of the user prompt handler
for when encountering a modal dialog.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/606)

Define Unexpected Alert Behaviour capability. Fixes #402

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/615)

Correct typo centrepoint to centre point

---

webdriver-spec.html

Closes #608
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/609)

`pointerUp` doesn't need to refer to keys.

---

webdriver-spec.html

Address issue #360.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/536)

Straw-man attempt at an introduction

---

webdriver-spec.html

This issue is already covered in `execute a function body` method.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/619)

Remove unnecessary issue from execute script

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/618)

Handle modal dialog when closing a window

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/620)

Editorial and typographical improvements to Unicode mentions

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/621)

Remove empty introduction chapter and shorten headers

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/622)

Remove local end issue from Nodes chapter

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/628)

Remove unnecessary DOM reference. Text has link already

---

webdriver-spec.html

Also convert related text to link.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/629)

Add missing dependency for qualified element name

---

webdriver-spec.html

Please don’t squash, since these changes are meant to be atomic.
Also, to be clear, there are no functional changes in this PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/630)

Wording and typography fixes

---

webdriver-spec.html

Fixes: https://github.com/w3c/webdriver/issues/658
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/672)

Use US American spelling in Dependencies chapter

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/677)

Correct socksProxyPort to socksProxy

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/675)

Fix proxy definitions

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/671)

Use US American and provide references to Get Current URL

---

webdriver-spec.html

The first commit is editorial, but the second is normative. I'm happy to submit them separately if it would aid review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/668)

Improve handling of "location strategies"

---

webdriver-spec.html

The two commits are not meant to be squashed together
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/686)

Capitalisations

---

webdriver-spec.html

#627
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/685)

Attempt to address #627

---

webdriver-spec.html

Fixes: https://github.com/w3c/webdriver/issues/665
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/670)

Drop empty introduction chapter under User Prompt

---

webdriver-spec.html

Fixes https://github.com/w3c/webdriver/issues/513
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/605)

Unify dispatch algorithm arguments

---

webdriver-spec.html

The commits are meant to be atomic, let me know to squash otherwise.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/698)

"Return to user"

---

webdriver-spec.html

This updates the name of the capability and adds details to
processing capabilities on how to use it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/702)

Update unexpectedAlertBehaviour to unhandledPrompt handler

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/704)

Update behaviour to en-US

---

webdriver-spec.html

The two diffs can be landed separately without merging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/696)

Actions all over again

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/705)

Go dont wait for local

---

webdriver-spec.html

This places it below all the pieces to do with input
source state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/708)

Move the definition of `input cancel list`

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/719)

Add issue reminding us to check if element is enabled

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/720)

Status requests do not have an associated current session too

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/722)

Wait for pageShow event on forward/back commands

---

webdriver-spec.html

But only optionally.
Closes #418
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/724)

`User Prompts`: include prompt text if present

---

webdriver-spec.html

Closes #662
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/726)

`Go`: handle meta refreshes on page loading

---

webdriver-spec.html

Closes #723
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/727)

`Actions`: Insist on an ID for each input source

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/697)

Make web element references normative

---

webdriver-spec.html

But they may not be.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/740)

Web Element references should be UUIDs

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/742)

Remove RFC 2119 words from a note around platform names

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/744)

Correct character case in URL template

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/748)

Respec warnings

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/753)

Convert old language: request to command

---

webdriver-spec.html

This also allows end-nodes to add additional
capabilities when returning results.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/751)

`Capabilities`: Clarify some points when matching capabilities

---

webdriver-spec.html

Fixes #699.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/752)

`Capabilities`: properly iterate when merging capabilities.

---

webdriver-spec.html

Fixes #700
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/750)

`Capabilities`: tidy up for loop when trying to match capabilities

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/763)

Convert some 'tick' text to links

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/764)

Correct reference to error in example

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/766)

Convert text 'connection' to link

---

webdriver-spec.html

This moves Execute Script to be Promise based and removes the
need for execute script async. The patch also updates the end
points to be like the Selenium JSONWP.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/756)

Move Execute Script to a promise based approach. Fixes #381

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/771)

Standardise formatting for null. Fixes #760

---

webdriver-spec.html

Closes #772.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/774)

Iterate over own properties in a more spec-y way

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/770)

Describe how to do clicks on Option elements. Fixes #663

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/782)

Add dependency for load event and link text

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/783)

fix typo for capabilities

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/784)

remove extraneous 'is'

---

webdriver-spec.html

These diffs shouldn't be squashed into a single one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/773)

Deserializations

---

webdriver-spec.html

Addresses #691.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/779)

`Actions`: properly release devices from active input sources

---

webdriver-spec.html

This matches the intent of the text.
Address part of #691
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/780)

`Actions`: minor clean up to link to active input sources

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/789)

Convert some text to 'Fire an event' links

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/801)

Fix link to issue tracker

---

webdriver-spec.html

He's landed some tests for the spec into the WTP project
and also contributed PRs and suggestions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/802)

Add Jim Evans to acknowledgements.

---

webdriver-spec.html

Closes #786
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/812)

Attempt to improve the langauge around setting a proxy

---

webdriver-spec.html

Fixes: https://github.com/w3c/webdriver/issues/821
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/822)

Correct capbilities typos

---

webdriver-spec.html

Closes #797
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/800)

`Navigation`: use `trying` when waiting for navigation.

---

webdriver-spec.html

Thanks to @ltetzlaff!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/845)

Improve browser chrome definition

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/853)

Move URL from Fetch to URL dependency. Fixes #836

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/856)

Fix some English typos and misspellings

---

webdriver-spec.html

This moves from doing a navigate that clears the history to doing
an overridden, or forced, reload of the document.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/851)

Use a force reload on refresh. Fixes #850

---

webdriver-spec.html

See https://github.com/w3c/webdriver/issues/847
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/857)

Remove issue that is not necessary anymore

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/860)

Correct English typo is to if

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/861)

Correct English typo be to is

---

webdriver-spec.html

The commits could be considered atomic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/859)

Some text converted to links

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/868)

Fix incorrect handling of configuration properties in new session

---

webdriver-spec.html

Handles undefined, matches it to the style of JSON clone.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/874)

Use match statement for JSON deserialize

---

webdriver-spec.html

No functional changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/876)

Use references and simplify language for clone an object

---

webdriver-spec.html

No functional changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/875)

Make JSON clone algorithm shorter

---

webdriver-spec.html

Editorial changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/877)

Reference getting a property throughout

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/880)

Fix "runthe" typo ("run the")

---

webdriver-spec.html

Describe the phrase "not in the same tree" in terms of the associated
algorithm (not as an algorithm that runs in cases where the phrase
applies).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/892)

Correct algorithm definition

---

webdriver-spec.html

Closes #863.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/898)

Clarify how a UUID is meant to be serialized

---

webdriver-spec.html

Fixes: https://github.com/w3c/webdriver/issues/664
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/897)

Use action primitives to define click steps

---

webdriver-spec.html

Closes #887
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/905)

The documentElement should be keyboard-interactable

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/911)

Fix stray </a> end tag

---

webdriver-spec.html

Fixes: https://github.com/w3c/webdriver/issues/916
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/917)

Fix reference to pageLoadStrategy capability

---

selectionchange.js

es6 specific changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/921)

Js updates to selectionchange file

---

webdriver-spec.html

Closes #925
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/927)

Add an `ignore state` for unhandled user prompts

---

webdriver-spec.html

Closes #919
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/930)

Fix handling of args when executing scripts

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/936)

acknowledgements: add Mike Pennisi to author list

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/937)

find: remove repeated algorithm step

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/946)

Go: Correct typo

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/967)

Fix inconsistent links

---

webdriver-spec.html

Closes #970
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/972)

Ensure all cookies are serialized

---

webdriver-spec.html

Fixes Issue #983
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/984)

Deserialize proxy capabilities should return success if all goes well

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/992)

Window state fixups

---

webdriver-spec.html

Closes #988
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/995)

Allow Set Window Rect to accept any valid Number

---

webdriver-spec.html

Closes #971
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/994)

Clearly indicate that webdriver can access HttpOnly cookies

---

webdriver-spec.html

Closes #885
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/997)

Make content editable elements clearable

---

webdriver-spec.html

Closes #884
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/998)

Make definition of `editable` clearer

---

webdriver-spec.html

Closes #888
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1001)

Element interaction: BODY only interactable in HTML docs

---

webdriver-spec.html

Closes #1009
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1011)

Clarify that network error and unsucessful HTTP result aren't the same

---

webdriver-spec.html

And then make use of `trying` when locating
elements.
Closes #993.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1015)

Make element locator strategies "tryable"

---

webdriver-spec.html

Closes #1016
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1018)

Timeouts: tighten definition to exclude implementation-specific timeouts

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1020)

window rect: drop window state field

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1022)

set window rect, maximize window: restore window first

---

webdriver-spec.html

Starts to address #895
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/999)

Layout should be complete before screenshots are taken.

---

webdriver-spec.html

Also avoids using normative language in the example.
Closes #758.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1027)

Clarify how intermediary nodes can modify New Session

---

webdriver-spec.html

Closes #374
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1034)

[Execute Script] Note about CSP policies being ignored.

---

webdriver-spec.html

Correctly, for both content editable and a regular input.
Closes #810
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1037)

[Element Send Keys]: set the insertion point

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1038)

Update execute a function body for modern ES/html. Fixes #869

---

webdriver-spec.html

And mark "unknown command" as 501 ("not implemented")
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1043)

Status Codes: mark not found resources as 404

---

webdriver-spec.html

[Navigation] Put navigation steps in the right place

---

webdriver-spec.html

Closes #1047
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1048)

Make note about platform names less confusing

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1050)

Use modern function calling techniques. Fixes  #1039

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1051)

executing script: validation fixes

---

webdriver-spec.html

This change is editorial.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1057)

scroll into view: improve definition of ScrollIntoViewOptions

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1058)

editable: editorial punctuation fixes

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1059)

get element rect: clarify that JSON Object fields are strings

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1060)

send an error: clarify that JSON Object fields are strings

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1061)

send a response: clarify that value field is a string

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1062)

new session: clarify the field types on the JSON Object response body

---

webdriver-spec.html

By linking to the URL spec.
Closes #1049
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1054)

Specify default ports in proxies if omitted.

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1085)

Fixed small typo :)

---

implementation-report.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1087)

Populate implementation report

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1089)

fullscreen window: restore window first

---

webdriver-spec.html

Section 17 - Actions always refers to *action sequence*s; so fix a type and change *actions sequence* to *action sequence*.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1095)

Fix typo: Actions sequence to Action sequence

---

CODEOWNERS

Suggest reviewers from the WebDriver admin group.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1109)

CODEOWNERS: add

---

webdriver-spec.html

Makes the first informational paragraph describing the command
non-normative.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1112)

navigate to: make description non-normative

---

webdriver-spec.html

The first paragraph is made into a note as to not confuse readers
about its normative requirements.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1115)

forward: make intro non-normative

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1116)

refresh: make description non-normative

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1118)

command contexts: make intros non-normative

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1148)

actions: input state is a variable, not a definition

---

results/2017-11/eg16.json
results/2017-11/html/all.html
results/2017-11/html/complete-fails.html
results/2017-11/html/consolidated.json
results/2017-11/html/less-than-2.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1161)

Add in Edge test results

---

README.md

This patch follows up on an action item that was assigned to me at
the WG meeting in Burlingame.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1160)

readme: fix urls and improve contribution advice

---

webdriver-spec.html

@gsnedders
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1167)

acknowledgements: add gsnedders

---

.pr-preview.json

https://github.com/tobie/pr-preview
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1172)

preview incoming PRs

---

CODEOWNERS

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1174)

CODEOWNERS: referencing a secret team does not work

---

webdriver-spec.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1077)
***
<a href="https://pr-preview.s3.amazonaws.com/andreastt/webdriver/pull/1077.html" title="Last updated on Dec 20, 2017, 2:04 PM GMT (d9ae35b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1077/6dc0341...andreastt:d9ae35b.html" title="Last updated on Dec 20, 2017, 2:04 PM GMT (d9ae35b)">Diff</a>

mathcing capabilities: fix list of well-known systems

---

results/2017-11/html/less-than-2.html

this removes results from tests that are not part of level 1 from the reports

Removing tests that are not included in Level 1

---

webdriver-spec.html

Closes #1046.
***
<a href="https://pr-preview.s3.amazonaws.com/shs96c/webdriver-1/pull/1185.html" title="Last updated on Jan 8, 2018, 2:48 PM GMT (741e829)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1185/69b5bad...shs96c:741e829.html" title="Last updated on Jan 8, 2018, 2:48 PM GMT (741e829)">Diff</a>

Add clarification about why we wait in `click`

---

index.html

Element retrieval commands have to invoke the user prompt handler (#1086)

---

index.html

sessions: fix duplicate definition of strict file interactability

---

index.html

See individual commit messages.

Clarify conformance chapter

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/JohnChen0/webdriver/pull/1361.html" title="Last updated on Nov 15, 2018, 7:53 AM GMT (b445e87)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1361/95db2ce...JohnChen0:b445e87.html" title="Last updated on Nov 15, 2018, 7:53 AM GMT (b445e87)">Diff</a>

Fix typos in "process a pointer move action"

---

.mailmap

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/webdriver/1372)

mailmap: fix ato's name and old emails

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/JohnChen0/webdriver/pull/1376.html" title="Last updated on Dec 1, 2018, 12:52 AM GMT (1884d75)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1376/d1769ca...JohnChen0:1884d75.html" title="Last updated on Dec 1, 2018, 12:52 AM GMT (1884d75)">Diff</a>

Fix typo in Element Send Keys to file input

---

w3c.json

Per https://w3c.github.io/w3c.json.html

Mark repo as host of rec-track work

---

index.html

Fixes #1391
***
<a href="https://pr-preview.s3.amazonaws.com/whimboo/webdriver/pull/1392.html" title="Last updated on Jan 9, 2019, 1:55 PM UTC (7164b39)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1392/52b0238...whimboo:7164b39.html" title="Last updated on Jan 9, 2019, 1:55 PM UTC (7164b39)">Diff</a>

Rename "Create Window" command to "New Window" (#1391)

---

index.html

Replaces ' with ’ for consistency.
***
<a href="https://pr-preview.s3.amazonaws.com/andreastt/webdriver/pull/1375.html" title="Last updated on Jan 30, 2019, 3:27 PM UTC (0eb0213)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1375/678d12c...andreastt:0eb0213.html" title="Last updated on Jan 30, 2019, 3:27 PM UTC (0eb0213)">Diff</a>

use typographer's quotes throughout

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/shs96c/webdriver-1/pull/1406.html" title="Last updated on Mar 25, 2019, 11:22 AM UTC (e5337a6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1406/ab946e6...shs96c:e5337a6.html" title="Last updated on Mar 25, 2019, 11:22 AM UTC (e5337a6)">Diff</a>

Change company affiliation for Simon Stewart

---

CODEOWNERS

I will continue to review PRs, but I want to be able to dismiss myself from reviews.

remove andreastt from CODEOWNERS

---

index.html

At TPAC we agreed to add the steps to handle user prompts where necessary throughout the spec. I am working on elementScreenShot and takeElementScreenShot commands, so it seems like a good time to add it there.
***
<a href="https://pr-preview.s3.amazonaws.com/thejohnjansen/webdriver/pull/1405.html" title="Last updated on Mar 22, 2019, 6:07 PM UTC (4ce49f4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1405/ab946e6...thejohnjansen:4ce49f4.html" title="Last updated on Mar 22, 2019, 6:07 PM UTC (4ce49f4)">Diff</a>

Adding the step to handle user prompts for screenshots

---

index.html

Added my name (not for this typo, but for previous contributions) If it doesn't count np!
***
<a href="https://pr-preview.s3.amazonaws.com/manoj9788/webdriver/pull/1455.html" title="Last updated on Oct 28, 2019, 2:55 PM UTC (91d180c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1455/81509c4...manoj9788:91d180c.html" title="Last updated on Oct 28, 2019, 2:55 PM UTC (91d180c)">Diff</a>

Correcting typos

---

echidna-manifest.txt
index.html

should be easier to push like that
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1460.html" title="Last updated on Nov 24, 2019, 8:07 PM UTC (567fae1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1460/bc70373...567fae1.html" title="Last updated on Nov 24, 2019, 8:07 PM UTC (567fae1)">Diff</a>

Minor tweaks to facilitate re-publication

---

index.html

Update "validate capabilities" section about handling of
extension capabilities, based on TPAC resolution
https://www.w3.org/2019/09/19-webdriver-minutes.html#resolution04.
***
<a href="https://pr-preview.s3.amazonaws.com/JohnChen0/webdriver/pull/1454.html" title="Last updated on Oct 23, 2019, 12:22 AM UTC (b9a1d99)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1454/81509c4...JohnChen0:b9a1d99.html" title="Last updated on Oct 23, 2019, 12:22 AM UTC (b9a1d99)">Diff</a>

Clarify validation of extension capabilities

---

index.html

section: 9. Timeouts
Current: Specifies a time to wait for the element location strategy to complete when location an element
Fixed:     Specifies a time to wait for the element location strategy to complete when locating an element
(location > locating)
***
<a href="https://pr-preview.s3.amazonaws.com/praveen4463/webdriver/pull/1463.html" title="Last updated on Dec 2, 2019, 4:31 AM UTC (13423c4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1463/2afae57...praveen4463:13423c4.html" title="Last updated on Dec 2, 2019, 4:31 AM UTC (13423c4)">Diff</a>

fixing a typo in timeouts section

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/Harsha509/webdriver/pull/1467.html" title="Last updated on Dec 7, 2019, 2:12 PM UTC (b1c2dde)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1467/ac8cecd...Harsha509:b1c2dde.html" title="Last updated on Dec 7, 2019, 2:12 PM UTC (b1c2dde)">Diff</a>

Modify: Updated irc channel link url

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1485.html" title="Last updated on Feb 28, 2020, 8:10 PM UTC (896e287)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1485/6a51e68...896e287.html" title="Last updated on Feb 28, 2020, 8:10 PM UTC (896e287)">Diff</a>

Change employment company for David Burns

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1490.html" title="Last updated on Mar 26, 2020, 10:26 PM UTC (df1b003)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1490/4265381...df1b003.html" title="Last updated on Mar 26, 2020, 10:26 PM UTC (df1b003)">Diff</a>

Add references to Same-Site. Fixes issue #1474

---

index.html

Fixes #1264
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1494.html" title="Last updated on May 19, 2020, 9:34 AM UTC (83631b3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1494/bb3e6d9...83631b3.html" title="Last updated on May 19, 2020, 9:34 AM UTC (83631b3)">Diff</a>

Correct Pointer move dispatcher typo

---

index.html

Per discussion in https://github.com/tabatkins/bikeshed/pull/1682.
This is mainly to minimize changes in https://github.com/w3c/webdriver/issues/1462.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1513.html" title="Last updated on May 29, 2020, 11:24 AM UTC (ac7f3ab)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1513/ee190be...ac7f3ab.html" title="Last updated on May 29, 2020, 11:24 AM UTC (ac7f3ab)">Diff</a>

Change status to Editor's Draft

---

index.html

1. Minor typo fixes in doc (Trivial Changes)
2. Came through this line
`You may add your name to the Acknowledgements section in your first PR, even for trivial fixes. The names are sorted lexicographically.`
So i've added my name into `Acknowledgements section` (not sure if this is valid)
***
<a href="https://pr-preview.s3.amazonaws.com/Harsha509/webdriver/pull/1546.html" title="Last updated on Sep 20, 2020, 12:30 PM UTC (844c79e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1546/afc3d5d...Harsha509:844c79e.html" title="Last updated on Sep 20, 2020, 12:30 PM UTC (844c79e)">Diff</a>

Typo fixes in doc

---

index.html

Fixes #1540
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1555.html" title="Last updated on Oct 16, 2020, 11:54 AM UTC (39c59d1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1555/99f7ced...39c59d1.html" title="Last updated on Oct 16, 2020, 11:54 AM UTC (39c59d1)">Diff</a>

"Release Actions" has to check for current and not top-level browsing context

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/jimevans/webdriver/pull/1567.html" title="Last updated on Jan 12, 2021, 5:10 PM UTC (42ff3c4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1567/4083b83...jimevans:42ff3c4.html" title="Last updated on Jan 12, 2021, 5:10 PM UTC (42ff3c4)">Diff</a>

Correcting error for Find Element From Shadow Root

---

.github/workflows/build-validate-publish.yml
index.html

See https://github.com/w3c/respec/wiki/respec-w3c-common-migration-guide
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1586.html" title="Last updated on May 7, 2021, 1:21 PM UTC (743b6af)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1586/861db6b...743b6af.html" title="Last updated on May 7, 2021, 1:21 PM UTC (743b6af)">Diff</a>

Update to latest respec

---

index.html

***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jun 17, 2021, 4:15 AM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.
:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Frawcdn.githack.com%2Fw3c%2Fwebdriver%2F771f92ed1546dfcc12ba4c21aedd4aaef386f650%2Findex.html%3FisPreview%3Dtrue)
```
📡 HTTP Error 429: https://rawcdn.githack.com/w3c/webdriver/771f92ed1546dfcc12ba4c21aedd4aaef386f650/index.html
```
_If you don't have enough information above to solve the error by …

chore: update previousPublishDate

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1607.html" title="Last updated on Jul 9, 2021, 1:34 AM UTC (50b1229)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1607/2f0a980...50b1229.html" title="Last updated on Jul 9, 2021, 1:34 AM UTC (50b1229)">Diff</a>

chore: update previousMaturity for FPWD

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/jboutsicaris/webdriver/pull/1611.html" title="Last updated on Aug 24, 2021, 9:52 PM UTC (d169409)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1611/3c94c9c...jboutsicaris:d169409.html" title="Last updated on Aug 24, 2021, 9:52 PM UTC (d169409)">Diff</a>

docs: unknown method description typo

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1616.html" title="Last updated on Sep 9, 2021, 5:24 PM UTC (afaa7cf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1616/3439b69...afaa7cf.html" title="Last updated on Sep 9, 2021, 5:24 PM UTC (afaa7cf)">Diff</a>

Fix the definition of get shadow root

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1619.html" title="Last updated on Sep 21, 2021, 2:51 AM UTC (69997f5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1619/bbb71e0...69997f5.html" title="Last updated on Sep 21, 2021, 2:51 AM UTC (69997f5)">Diff</a>

Attempt to fix some Echidna errors

---

.github/workflows/auto-publish.yml
index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1620.html" title="Last updated on Sep 21, 2021, 3:12 AM UTC (ca142a9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1620/69997f5...ca142a9.html" title="Last updated on Sep 21, 2021, 3:12 AM UTC (ca142a9)">Diff</a>

Fix various markup errors

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1621.html" title="Last updated on Sep 21, 2021, 3:26 AM UTC (174cb6f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1621/66f2c00...174cb6f.html" title="Last updated on Sep 21, 2021, 3:26 AM UTC (174cb6f)">Diff</a>

chore: update shortname in config

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/jimevans/webdriver/pull/1631.html" title="Last updated on Nov 10, 2021, 5:17 PM UTC (0b65781)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1631/56f84e6...jimevans:0b65781.html" title="Last updated on Nov 10, 2021, 5:17 PM UTC (0b65781)">Diff</a>

Explicitly specify returning shadow roots from script

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/robocoder/webdriver/pull/1645.html" title="Last updated on Mar 15, 2022, 12:47 AM UTC (c0ca14c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1645/4cf85a8...robocoder:c0ca14c.html" title="Last updated on Mar 15, 2022, 12:47 AM UTC (c0ca14c)">Diff</a>

Typos and inconsistencies (e.g., US vs UK spelling).

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/Igalia/webdriver/pull/1689.html" title="Last updated on Oct 19, 2022, 12:37 PM UTC (0409e1c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1689/0707ea4...Igalia:0409e1c.html" title="Last updated on Oct 19, 2022, 12:37 PM UTC (0409e1c)">Diff</a>

Editorial: use proper cross-references for DOM, FileAPI and some of HTML.

---

index.html

Follow-up from #1673 which was incomplete. This PR updates the visible changeset of the Selenium project as well.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1692.html" title="Last updated on Oct 25, 2022, 2:42 PM UTC (cb9511e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1692/9636c6d...cb9511e.html" title="Last updated on Oct 25, 2022, 2:42 PM UTC (cb9511e)">Diff</a>

Fix broken Selenium changeset for atoms export

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1767.html" title="Last updated on Nov 14, 2023, 3:52 PM UTC (9999a4e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1767/cad2a23...9999a4e.html" title="Last updated on Nov 14, 2023, 3:52 PM UTC (9999a4e)">Diff</a>

editorial: export "error code" dfn

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1766.html" title="Last updated on Nov 14, 2023, 3:52 PM UTC (681c423)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1766/cad2a23...681c423.html" title="Last updated on Nov 14, 2023, 3:52 PM UTC (681c423)">Diff</a>

editorial: export "try" / "trying" dfn

---

index.html

Closes #1773.
@AutomatedTester and @jgraham mind reviewing? Thanks!
***
<a href="https://pr-preview.s3.amazonaws.com/whimboo/webdriver/pull/1778.html" title="Last updated on Dec 6, 2023, 11:31 AM UTC (eb3f210)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1778/e91f9d8...whimboo:eb3f210.html" title="Last updated on Dec 6, 2023, 11:31 AM UTC (eb3f210)">Diff</a>

Bump Selenium atom's revision to fix issue with "Get Text" and closed ShadowRoot

---

index.html

Fixes #1783.
@jgraham and / or @sadym-chromium mind reviewing? Thanks!
***
<a href="https://pr-preview.s3.amazonaws.com/whimboo/webdriver/pull/1784.html" title="Last updated on Jan 23, 2024, 6:54 AM UTC (9e85675)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1784/d08a954...whimboo:9e85675.html" title="Last updated on Jan 23, 2024, 6:54 AM UTC (9e85675)">Diff</a>

Bump Selenium atoms revision for latest fixes for "Get Visible Text"

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/pull/1794.html" title="Last updated on Feb 15, 2024, 9:26 AM UTC (9966b03)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1794/0e8cc51...9966b03.html" title="Last updated on Feb 15, 2024, 9:26 AM UTC (9966b03)">Diff</a>

Editorial: fix link to the capabilities var

---

index.html

In https://github.com/SeleniumHQ/selenium/commit/33c6b7841a59aaaad55744909c0600f066fd5593 the atom was fixed to correctly find capitalized text containing and underscore.
@jgraham or @lutien mind reviewing?
I'm going to add wdspec tests via https://bugzilla.mozilla.org/show_bug.cgi?id=1888004.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on May 8, 2024, 1:04 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [HTML Diff Service](http://services.w3.org/htmldiff) - The HTML Diff Service is used to create HTML diffs of the spec changes suggested in a pull request.
:link: [Related URL]([object Object])
```
<!DOCTYPE html><html …
```

Bump Selenium revision to include fix for "Get Element Text" atom

---

index.html

@jgraham mind reviewing? Thanks.
***
<a href="https://pr-preview.s3.amazonaws.com/whimboo/webdriver/pull/1816.html" title="Last updated on Jun 7, 2024, 1:57 PM UTC (0f5ba6a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1816/48a221b...whimboo:0f5ba6a.html" title="Last updated on Jun 7, 2024, 1:57 PM UTC (0f5ba6a)">Diff</a>

Fix handle any user prompts to set the type for beforeunload prompts

---

index.html

Addresses #1598.
***
<a href="https://pr-preview.s3.amazonaws.com/alexnj/webdriver/pull/1839.html" title="Last updated on Sep 12, 2024, 4:19 AM UTC (9af8e07)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1839/7a23ea0...alexnj:9af8e07.html" title="Last updated on Sep 12, 2024, 4:19 AM UTC (9af8e07)">Diff</a>

Export "local end" dfn

---

index.html

Fixes #1923.
This reverts commit 957235efd088d36239e7b850c84b04b2d11f2f80.
***
<a href="https://pr-preview.s3.amazonaws.com/whimboo/webdriver/pull/1924.html" title="Last updated on Sep 1, 2025, 6:32 AM UTC (dc85d7e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webdriver/1924/e380bf3...whimboo:dc85d7e.html" title="Last updated on Sep 1, 2025, 6:32 AM UTC (dc85d7e)">Diff</a>

Re-add "instant" scroll behavior as default for scroll into view
